const dashboardData = {
  "run_metadata": {
    "run_id": "2026-05-12-run",
    "run_date": "2026-05-12",
    "companies_investigated": 8,
    "companies_excluded": 0
  },
  "evaluations": [
    {
      "company_name": "Grupo Osborne",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "B",
      "asia_tier_evidence": "Grupo Osborne has an Asia & Pacific Director (Maria Varela) and an Area Manager Asia Pacific (Javier de la Vega), indicating an APAC regional structure. They recently (April 2026) appointed Octopus (APAC) Holdings Limited as their principal distributor in Singapore for Asia-Pacific growth, including a strategic equity investment. Japan is identified as a strategic market for the group, with products distributed through established import and distribution partners.",
      "industry_primary": "Food, agribusiness, protein, beverages",
      "industry_weight": "High",
      "company_size": "Mid",
      "employee_count_estimate": 616,
      "why_it_fits": "Grupo Osborne, a distinguished Spanish producer of wines, spirits, and gourmet food, is an excellent fit for Wendy due to its strong and recent commitment to the Asia-Pacific region and Japan. The company's Spanish HQ is directly in Wendy's rubric scope. With an established APAC regional structure, including an Asia & Pacific Director and an Area Manager for Asia Pacific, the company is actively pursuing growth in the region. Recent strategic moves, such as the April 2026 partnership with Octopus (APAC) Holdings Limited to drive Asia-Pacific growth and develop products tailored for Asian palates, demonstrate a clear and timely focus on markets like Japan. Grupo Osborne also joined the Spanish Chamber of Commerce in Japan in February 2026, explicitly stating Japan as a 'strategic market'. Wendy's cross-functional commercial background across diverse industries, particularly her experience in B2B contexts, marketing, operations, pricing, and supply chain, directly aligns with the needs of a company expanding its premium food and beverage distribution and brand positioning in Japan. Her business-proficient Japanese (JLPT N2) and native Spanish are highly valuable for bridging communication between the Spanish HQ, APAC regional teams, and Japanese distribution partners.",
      "confidence": "High",
      "confidence_reason": "Strong evidence from multiple recent sources (April 2026 news, February 2026 corporate membership) confirms Grupo Osborne's active expansion in the Asia-Pacific region and specific strategic interest in Japan. Key personnel for APAC operations are identified, and company size is clearly stated.",
      "role_archetypes_likely": [
        "Trade Marketing Manager / Specialist (Asia, APAC, Japan)",
        "Business Development Manager APAC or Japan",
        "Sales Manager Japan (B2B contexts)",
        "Product Manager (commercial / category context)",
        "Channel Manager"
      ],
      "flags": [],
      "suggested_next_action": "Message Maria Varela, Asia & Pacific Director, Grupo Osborne. (Direct LinkedIn URL not found in search results.)",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFdQgQQieYqrerSmF9SD8BsJEkxOFi0i85rxEum9QwXnw0AJI8CiYpQGHOtDr97aaItFsXbUg053Qn8iZDh2vAvlg4AD_H2msmLhgQWe70WCgQlR0MPhrqVG1lwfr7YYAMQwCfKcN5ra_3VgzuRWfwcjeDHthOtq06s=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEG0DQPOsf56LZaTLoSRw1dVLi3qXr7LbcvndDPVjiq34N46gq2wFoRvGsW8Q6InT6PgBnB65PzZC5Ej5E-u6OSP_r4jpcD03ckJkg8pwHH4XmyBa9NQvuCKidOc6Fh940idbPrtQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFT9bqFPARogqrqzGmcZkmOd4bkYx_ebF3gVEd-r4F5jyOPcxetfg0FTSAXlFOyZjB8XYBnxMZr52q1GWXtC-Qh7SaIaPWN0SgbhwZNt9O87WCVa5B7p3twPu__KOJjHXfXzOkPTjpmkDdSjvCZyUauKliNAlKPP5QxvwhGMQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHp2H52fp4WD75zaiE80G9X8WS0ZCeUTHBHdbxVsMWqGksQeMxITKGF2pH1GleU-F6m6kC2jhb4ivLtzkRNQLCdiIXiaDvpy6vD-95xsScmi3jnxiCz21aF7HRIlq-97FzGXRn6IDhZDg8Dewn4FFVQP7IdrzM8jQk17FAJdpjCS2keESbPgrVVE4v7vXreA_rWZ-Z7YLkbn_ToG5zxUc43DLu9u-BziAklQjtYZF46SZ94",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFUVIr6fWlrP1ntZZTs6BJM-m3joVzeO8LVJc1ZK_tLVS7RzgTF8rjL0pwfQi_83IksYua_gwZDr5LsI6w6WMKzPhsrwHtSUuYDMLpMM6VdHKVW-DKC7I3hNYBVfeu50dM_JWF2UlJBolJmWIA-oGyCyJA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFO-lKEl2t34lKYz9HQKFKBieMSpNnQ6_xGIJkvazKBwqauuQnfBZDcr5FeDddE_53NuEOn2m57qV5pWslyNfPPn5LdldVpwxIa3DaUz9HfvrQasGGn5HFn1IVy1_8uvlnAH-HVedQFyktXPD4Lbl366dNPRIjrU-SLUn-8bbAUMbxLf8qtk5Y_q-iUvCfToq0Yk41EI89Zv2LQGcOQ6dvtlsa_PpiyEqwwZ4NXmBqJf-4HIj7v-A==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE_N0xTqV1m9emPflhHYZ2mm_19D3TQ8sutxDuyp7fGXMgYGRXK12_Fl3VVIL6e5_M54PKh8R1JgNgfPOyuPIwm3PXkozNpXuXnx8WyNMVK805dc4avnPgtbkfZzdxi3wA1nx1z-eHY-qUponqM"
      ],
      "search_queries_used": [
        "Grupo Osborne Japan office",
        "Grupo Osborne Tokyo subsidiary",
        "\u30aa\u30ba\u30dc\u30fc\u30f3 \u65e5\u672c\u6cd5\u4eba",
        "Grupo Osborne Asia Pacific",
        "Grupo Osborne Singapore office",
        "Grupo Osborne employee count",
        "Grupo Osborne LinkedIn",
        "Grupo Osborne Japan news 2024 2025 2026",
        "Grupo Osborne Japan corporate membership",
        "Grupo Osborne Japan events",
        "Grupo Osborne Japan Country Manager LinkedIn",
        "Grupo Osborne Asia Pacific Head of Sales LinkedIn",
        "Spanish Chamber of Commerce Japan Grupo Osborne LinkedIn",
        "Grupo Osborne scandal",
        "Grupo Osborne downsizing",
        "site:linkedin.com \"Maria Varela\" \"Grupo Osborne\" \"Asia & Pacific Director\"",
        "site:linkedin.com \"Javier de la Vega\" \"Grupo Osborne\" \"Area Manager Asia Pacific\""
      ],
      "verification_gaps": [
        "Direct LinkedIn URLs for key contacts like Maria Varela (Asia & Pacific Director) or Javier de la Vega (Area Manager Asia Pacific) at Grupo Osborne could not be found in the search results."
      ]
    },
    {
      "company_name": "BCN Brand",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "C",
      "asia_tier_evidence": "BCN Brand, a Catalonia-based accessories and footwear company, announced plans for expansion into Japan in November 2015, including agreements with Japanese department stores like Takashimaya, Hankyu, FootMind, FootPride, and Akaikutsu in cities such as Tokyo, Osaka, Nagoya, Yokohama, and Hakata. The company also planned to create an e-commerce platform for the Japanese market. As of the current research (May 2026), no recent (last 12 months) public information was found to confirm the continued active physical presence, establishment of a registered Japan entity (KK, GK, branch) with local staff (Tier A), or an APAC regional hub (Tier B). The official website primarily caters to the Spanish market with Spanish contact details.",
      "industry_primary": "Retail, Footwear & Accessories",
      "industry_weight": "High",
      "company_size": "Small",
      "employee_count_estimate": 13,
      "why_it_fits": "BCN Brand, originating from Barcelona, Spain, presents a strong geographical fit for Wendy due to its Spanish HQ, aligning with her native Spanish proficiency and the rubric's 'Spain' inclusion. The company's prior expansion into Japan in 2015-2016, involving agreements with major Japanese department stores, indicates a historical commercial interest and presence in Wendy's current location, Tokyo. This direct market entry strategy, along with plans for an e-commerce platform, aligns with Wendy's cross-functional commercial background, including marketing, operations, and B2B experience (e.g., managing retail services at Sodimac and corporate market at Cocha). While recent signals about their Japan activity are limited, Wendy's N2 Japanese proficiency and Japanese nationality could be a significant asset for a small Spanish brand looking to re-energize or solidify its presence in the Japanese market, potentially bridging cultural and business gaps and supporting renewed growth initiatives. Her experience in trade marketing and business development, particularly in multinational retail environments, directly applies to the challenges and opportunities of an international accessories and footwear brand like BCN Brand.",
      "confidence": "Low",
      "confidence_reason": "Confidence is low due to the lack of recent information (past 8-9 years) regarding BCN Brand's ongoing operations and specific entity status in Japan. The most relevant information about their Japan expansion dates back to 2015-2016. While there was clear intent and initial agreements, current operational details and the existence of local staff or a formal entity could not be verified. Additionally, no verifiable LinkedIn profiles for key personnel directly associated with this specific fashion/accessories BCN Brand and its international operations were found.",
      "role_archetypes_likely": [
        "Trade Marketing Manager / Specialist (Japan)",
        "Business Development Manager Japan",
        "Sales Manager Japan (B2B contexts)",
        "Marketing Manager Japan"
      ],
      "flags": [],
      "suggested_next_action": "Email hola@bcnbrand.com, the general contact email found on their official website, expressing interest in their Japan market activities and potential future commercial roles.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHFHVEQASbpQpwC3MKmKsuc2lE6M8jEQY7UAqiwJMIOyWJ2ez-h9kqAMoNUxQIcx1T3i177tM5yMrinz7NM55SiHgKVfoI-JzwFZvPTZfzZkw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEJnAv6JYdkzQ3VYfDz22_EMQLQvvpbj8Eq5edATiBXGaI38YRRuvg-0EsMITGVnJVyy2HK5jTUxEEHWzdWQGgMqcNRK6rHjk_ICDEf2v5QuZbDk_1ZHql6y0g8V6WpH_Nbw_LZ_r6MiRY7fENWFFWmVjCKz2sa8aKEcgM_xruJ5Ml0CnBvMxc0P5YOTg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEbFZVGJ1Iv2RxhUOmm-vdjFMwB0W7nhWcc16y7ngdrwod1rs5btzYVl3DFaqiDwnQ-pNfO9aixE9iRr3_5rP6ZYyeFxiBsAisuyOhqWL6RqSgEdtqCmEK5LOBNFkO4v9qn6b3vCXeW8xhWMIwzbeXsiGu00ZmFMnBCQwc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHhAqQIQlFhaPmqTXasdkmgCAKryHF7fSYvAEuXTJOi1Rqjrd9l_yD989LQ0LMDNnI3sRrgDtAIoHmYSyVnKSumGdi5rHsu-o9_uxu_B61mS_5Zub7mZP_ePI_GzL3yAm-IexhqK17SuqAzA7Qi1HQFDWG8mQvdUd-WEPUOc5KTcN3wH_gU6dA7JI0Dlw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGCq4e9Ym2v89NCL0Jp8RtEcovKROGV8JNZivUUOFKGeomvwi6q_QFstv8_r4-y_nZgEFpnJ4oC4QWlXDFJcmbG-3m4VLQojJSTvc_W5KRTKJEDyVmER2GU4wy3Gkk3y6YqGjxOzg-cXmaZXi31CwfWlmucoBr9_kgPdAhXh_0FkA-B0yfvNKfKVj4PTA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEXoAU2jdl0xPxR_xWFiufRDsLNamQBk1DcySxxqNLVMVZ-kM3ZASaMMoHL5NBRWRO5sbqjx-m8yH0hkyxsp61jqXlHv0UV9ocqcOzfLQe6Xk3zHJ_jsxTTG01b7MxmtpTex2MZxVNeeXsdF4CReHQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE06dHdt8wgSh2mNHERWKKCffCthGnz-kJ9zA2_XjHSdVXUIwDTB5lKrB766ZmAsdGPhxS4duGTkG2gfzfofoHtyu7LUd_5O1wVGWGixW1mc0lT9KRzWBZOybawIWWDM1KA"
      ],
      "search_queries_used": [
        "BCN Brand company information",
        "BCN Brand headquarters",
        "BCN Brand Japan office",
        "BCN Brand Tokyo subsidiary",
        "BCN Brand Asia Pacific operations",
        "BCN Brand Japan expansion news",
        "BCN Brand employees",
        "BCN Brand LinkedIn",
        "BCN Brand Japan department stores",
        "BCN Brand Japan e-commerce",
        "BCN Brand scandal",
        "BCN Brand downsizing",
        "BCN Brand footwear Japan current operations",
        "BCN Brand accessories Tokyo office",
        "BCN Brand fashion Japan LinkedIn",
        "BCN Brand Pablo Caralps LinkedIn",
        "BCN Brand Japan distributor 2023 2024",
        "BCN Brand e-commerce Japan active",
        "BCN Brand fashion company LinkedIn",
        "BCN Brand (footwear accessories) official website"
      ],
      "verification_gaps": [
        "Confirmation of the current operational status and scale of BCN Brand's presence in Japan beyond initial expansion announcements from 2015-2016.",
        "Identification of a specific registered Japan entity (KK, GK, or branch) with local staff.",
        "Identification and verifiable LinkedIn URL for a key contact (e.g., founder Pablo Caralps or a Japan/APAC specific manager) for this particular fashion/accessories BCN Brand."
      ]
    },
    {
      "company_name": "Werfen",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "A",
      "asia_tier_evidence": "Werfen has a registered Japan entity, \u30a2\u30a4\u30fb\u30a8\u30eb\u30fb\u30b8\u30e3\u30d1\u30f3\u682a\u5f0f\u4f1a\u793e (IL Japan K.K.), located in Tokyo, Minato-ku, Mita 1-chome 3-30. The Spanish Chamber in Japan explicitly states that Werfen has a legal entity in Japan and names a Representative Director.",
      "industry_primary": "Healthcare/Specialized Diagnostics (In-Vitro Diagnostics, Medical Devices)",
      "industry_weight": "Lower",
      "company_size": "Large",
      "employee_count_estimate": 7000,
      "why_it_fits": "Werfen is a global leader in specialized diagnostics headquartered in Barcelona, Spain, aligning perfectly with Wendy's preferred HQ geography. The company operates a direct subsidiary in Tokyo, Japan, named \u30a2\u30a4\u30fb\u30a8\u30eb\u30fb\u30b8\u30e3\u30d1\u30f3\u682a\u5f0f\u4f1a\u793e (IL Japan K.K.), confirming a Tier A Asia Operations presence and eliminating relocation/visa concerns for Wendy, a Japanese national. With a global workforce of over 7,000 employees, Werfen offers the robust structure of a large multinational. Wendy's commercial, data-driven, and cross-functional background, honed across various multinational environments (including ICT at Fujitsu), fits well with Werfen's need for commercial expansion and market penetration in specialized diagnostics. Her experience in marketing data management (e.g., leading the renewal of a Marketing Data Portal at Fujitsu [cite: CV]) and coordinating client-facing events [cite: CV] aligns with Werfen's ongoing commercial activities and recent local initiatives, such as the opening of the 'Werfen Library' for medical professionals in Japan in October 2025. Werfen also showed strong organic sales growth in Latin America in 2025 (+10%), indicating a global commercial drive where Wendy's multilingual (Native Spanish, Business Japanese, Fluent English) and cross-cultural coordination skills would be highly valuable in bridging regional strategies.",
      "confidence": "High",
      "confidence_reason": "Strong evidence for HQ location, Japan entity (Tier A), company size, industry, and recent Japan-specific activities. The company's global career portal also lists Japan as a direct operations country.",
      "role_archetypes_likely": [
        "Marketing Manager Japan / APAC",
        "Business Development Manager APAC or Japan",
        "Product Manager (commercial / category context)",
        "Pricing Manager"
      ],
      "flags": [
        "Roles requiring specific technical credentials Wendy doesn't have (e.g., highly specialized biochemistry or medical technology backgrounds for certain Application Specialist roles) might require a steeper learning curve or be a soft disqualifier.",
        "Country Manager / Japan-public-facing roles where near-native Japanese is implicitly required (while the current Representative Director is non-Japanese, some very public-facing roles might prefer native proficiency for complex stakeholder management)."
      ],
      "suggested_next_action": "Message Israel Crespo, Representative Director for Werfen Japan (\u30a2\u30a4\u30fb\u30a8\u30eb\u30fb\u30b8\u30e3\u30d1\u30f3\u682a\u5f0f\u4f1a\u793e), on LinkedIn. (Note: A direct LinkedIn profile URL for Israel Crespo was not explicitly surfaced in the search results; the provided URL is for Werfen's general careers page on LinkedIn, which is the most specific direct LinkedIn channel available through search.)",
      "sources": [
        "https://www.werfen.com/en/about-werfen/at-a-glance",
        "https://www.leadiq.com/companies/werfen",
        "https://owler.com/company/werfen",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEw8D81rowY-zgnJjwmHzPH-D74MnvKSRe6SbSdeId4rYDWUUIzBiRSG1sHg8Bwcfys83aXknVT5IqdGyzxxV6yCUksHDt_l48mOu4L2Ax5rsMKVCbB2F-SysDHdQ9MJMX-wCUIpn-0T1LmyXvc-I3PjbO_NlY",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQERZj-SElcjIiPqGWFxWoK1w1J63p30vszTFbDTq9iI5WpkwaDciTrQWykyxMKo5R205YnXb6IZCFINggNbkxM6Qm001P17t5f8D-QEg3jv1K4D2KdmasJzFM1X2W7BscK4hA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGwtmcRuhhziV5RTbpL2o48fG4CO-gaxfeMFcNe1DybAXmPmqNPzLrPV4H80zFZR4OrP0eyiKf5gOPK50nJxFwVHTg4xH_RXnpJcAHNBfdgL5mwPYTrPRWq5-DiYA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHO-y6sQctnZ7YK1ll95hm1oiu2abgUpCAbKyoUzK98UtMflrP7-1aN0aejiyrW3OpYyPbW8PzgeGRSI_QiulaEFDbq3ug_dSrFBV6fTN3TGl5aWPt0jDnUx0s3q_RYlthkxcQ=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFHcTFdpL8XZ2R5qiTxP86fbbhjC5wz6Pm3_YGHrf-nYMYx4HfN5nShpBhsnKIc2DrOrYpwN2REN1lMJB_yCmHMwpGMZo-VO_4zfka9YCxysCxyMYxnugDDph5zc8KNaQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHYtonKvTdDU8mYRTez0-_DHs201XkIaSnepvrNzGoaZV4MZLDl2uwfHYktcz5WEBzfG9YDf3vqV9f2vi_BTlgwGaVI-iry43FlmcFmudc3-lyKm7k=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGQ83_2VupYviOGU6pQFWvI-F1fMqU9q3Ngdmvc2DGeSD3SImG5WVVc-0r20kRnlYTGf7gtvDJOawAczyyI4oBcfhy8CDFK8gdbuUg8N0m0RNZzB1JDhswmzGxwPfMXNGyTwDkun9pg",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEP0u9Tam8nVgc0EvGNpSOhCkiCQkvOHrKDqpBmLg6zWb9M4mCd1ZgPV1DgcseSeTjSHcKsrvM1HKllqadFzGrE9jtmbhpXvXhr3hZhydpqHz8Ya5RvNZFWWYBi3-iTTP0Zls4aNg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHmc_GNdlHx8Z-jefM-9gI8LvE6cJWhoCgEFK4Fxwy98reNGBQ6V_rLpuo9YvBuM8nt6RQmFvSQz0GKhB_OutDkCCgJ1BRc2iOcPs_p6pras7fQ4I90OBR3cQ55NeKBosNhzAjxBtxFk_hZgv5sBhjVufE8Z2w378t3Y4u7e_VwYJuBj7ZZhfrDGV_MLd73sBY9sLEkkpSGqJWf",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH9U9Euj_QG98YXCgpmpHRoSXVyTw8540Qgc4-As4G21F0BpL00xm-vKMYXbT_naArhTuXDAWhg9JQXdZ6InOes4V4UBW7qZUwC7nx0F2Kjw--Pk5nPqhEXQkyblViLgho=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGvTb0hWlE483fPvCL_KA0SnG7yxZ58DvDK7jBnvFnr4jGbeSdyt9Euqq2g5pgNFs-7B9u_JOzsa3CzBHiNueVk2Ngr1HQIFnaJs6muuX8dBPOSroFQI4SSHwv75q2ByImrjoyq",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQErJqDe0mVmakpk5QOfHd_Fuc2ReiReDkxax3iQL0O3IjMCj8tihuC1OocB2o9n-tTEcb8SZpRutrpHM4IzpRTWoqTq9oibS7Di1-Ec23Sfb3onnkYWCAURoMTfqjCSoWSKPqVK",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFXPKQYZoZ57uksHTva1cp-6K8ln00UMVjWB1M0wgvCcZpCk6ypu9OsxoFlW6uhWVL0blFamMt_iNvHLt5dF0K2OiZnF-DZjG68gqeGJLC2Te2kJmIU_k8="
      ],
      "search_queries_used": [
        "Werfen Japan office",
        "Werfen Tokyo subsidiary",
        "\u30ef\u30fc\u30d5\u30a7\u30f3 \u65e5\u672c\u6cd5\u4eba",
        "Werfen Asia Pacific",
        "Werfen Singapore office",
        "Werfen employees",
        "Werfen LinkedIn",
        "Werfen Japan news",
        "Werfen Asia news",
        "Werfen press release Japan",
        "Werfen Japan Country Manager LinkedIn",
        "Werfen Asia Pacific hiring LinkedIn",
        "Werfen Japan Talent Acquisition",
        "Werfen scandal",
        "Werfen layoffs Japan",
        "Werfen company profile",
        "Israel Crespo Werfen LinkedIn",
        "Israel Garcia Crespo Werfen LinkedIn",
        "Werfen Talent Acquisition LinkedIn",
        "Werfen Japan employee sales marketing LinkedIn",
        "Werfen Asia Pacific marketing director LinkedIn"
      ],
      "verification_gaps": [
        "While Israel Crespo is identified as the Representative Director for Werfen Japan (\u30a2\u30a4\u30fb\u30a8\u30eb\u30fb\u30b8\u30e3\u30d1\u30f3\u682a\u5f0f\u4f1a\u793e), a direct LinkedIn profile URL for him could not be explicitly retrieved through the conducted web searches. The 'suggested_next_action' therefore points to the company's general careers presence on LinkedIn."
      ]
    },
    {
      "company_name": "Freixenet",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "A",
      "asia_tier_evidence": "Freixenet is part of the Henkell Freixenet Group, which has a registered Japanese entity called Henkell Freixenet Japan Inc.. This subsidiary is involved in the promotion, sales, and support activities for the group's brands in Japan.",
      "industry_primary": "Beverages",
      "industry_weight": "High",
      "company_size": "Large",
      "employee_count_estimate": 8300,
      "why_it_fits": "Freixenet, a Spanish cava producer, is now fully owned by the German Henkell Freixenet Group. Its HQ in Spain aligns with Wendy's rubric for in-scope geographies. The company has a strong, explicit focus on expanding its 'Global Icon' brands, Freixenet and Mionetto, in the Asia-Pacific region, including Japan, with recent activities and trade show appearances in Singapore in May 2026 and May 2025 highlighting this strategic push. Henkell Freixenet Japan Inc. serves as a local subsidiary responsible for sales, promotion, and support, indicating a direct need for local commercial talent. Wendy's extensive cross-functional commercial background across marketing, operations, pricing, and B2B in multinational environments makes her an excellent fit for roles like Trade Marketing Manager, Business Development Manager, or Marketing Manager, driving growth for these global brands in the Japanese market.",
      "confidence": "High",
      "confidence_reason": "Strong evidence exists for HQ location, direct Japan entity, industry, overall company size, and recent strategic focus on Asia-Pacific/Japan. The connection to Wendy's profile is clear given her commercial and marketing background and language skills.",
      "role_archetypes_likely": [
        "Trade Marketing Manager / Specialist (Asia, APAC, Japan)",
        "Marketing Manager Japan / APAC",
        "Business Development Manager APAC or Japan",
        "Sales Manager Japan (B2B contexts)",
        "Key Account Manager Japan / Asia",
        "Product Manager (commercial / category context)"
      ],
      "flags": [
        "Country Manager / Japan-public-facing roles might implicitly require near-native Japanese, which Wendy's JLPT N2 proficiency (business communication) may not fully meet."
      ],
      "suggested_next_action": "Search LinkedIn for 'Country Manager Japan Henkell Freixenet' or 'Marketing Director Japan Henkell Freixenet' to identify key personnel and review their profiles for potential direct outreach. For example, look for profiles with a focus on commercial growth in Japan or APAC.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHJkN8UZuNuY0pYvbgMFqNULAAT3IMOYJMhZtCTobpLdEEtWbFORyYJenpmmY2G4GaLitg3PywV5rPVZS61sMA6Emuh-wk4tFdYWd9ytO2UDTCTjyvyhjLiql4kzKUw28Vqut-YFhN5mHwwbIR9J9SXefF2XGLQqZk6uwTc6QcAhI2RdGnvza3tDxQgtvZ9cmW3JAV4tyRWrqfu_nsC1xffSGdjKWG0-Ow=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFnhoIkC9mpqz71WL5irMLC4D8_1vXxa5yEsXQ9z04FIhy8clv-j4SKf9C0ZyUpmJb4cCRh7HrL7WL_FnBVBBXhAMnor-ThOoo7EBUl0g299V5wxEjsDj85z167fYO5jtsfPg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFHdZbLBWnau-_GA49gpl3-8c-sBtszkFQZHTAVfkEMfcwu9Owp9YIEPfpfp4K5EwBtNQkxm23Bt7Nf40kvHUz2DN7vsj7upQ6i0ViNJHAqqMp3_Mji34ZGyAUaGoE_qNA5SrbbVdTDwz5Igw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEvoSDRthF80wipHuOgzEIcRHYdI9wwjrHRj_kFLqlh6mcgGDhnDEGIDRxw8iW0mB1Bpci7pzYv1v4MSCQvB20Pv3_PFWKYYjuBBy_OYxB1vwQyGTivHtEPkeYURN4pJmYNvQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEHXsMi0tew8UG3lNjOqrNYtHjx9HhVLyrvCW4rLePPkiWO947_u3kjs2U5NGZsxLr4d8Qq7Mu1-1RvQQ7UW2JCwSx_Gg_7bUJREr_iWVsFt3CcDgG4TKHUusFKOo64iE9AbBzoR1PjB3zMv1Nt7PEQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFPK2P1xsPoy7TDNiFRmpx-ZUPjcoUHeC1S3pQB1JcEjdNGyUNAU8p60UzarKHBiT4_LIB53azA66YTDoC5e6gNctxUBVWPcemuJSrMZq4zTHarAE0Aum6jUfC_2mF4f2ikg_hthtVx4X4MOGBvtw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGIbBh8RBDumRm-7-_uBp5HpnqDYLnobYvQW2BitXl2wWMnYoWiy-8xgZ3IeyFe_C_vS9HScYvuchGNWA2XwEjg6K5NDcQTP1bThb9EVTtdqSQxGHNJBr3rF03rhQA40T3vVafxV8leKRlPZjGepvPHA22RlfP2ppldgGap1TTtdu_oSJQa74Bq9-1MafKWvgLFYNxoYBNJsX0p8W0=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFW4LKbtiW_XWEGMl6am9_QsYsZZ-Z5tkOV-sQA5g1FktYZCXJEvNnSJvYmS-QSdHe4zMV_BMA65kGqIDaf4K6HMUacLkyPrjgq-kd15A5KZOc5Zs9m1x1Jpg8d0SeLnkGKqUCGBKTiNIWOdXs_piZxmymr",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFVwVBSYNtW9nEBR1jgoCUekuPCbX4oejap33yYGMaahG_-13bl6irxp-2gfUzI_6x8FPlYYCIICGneqPSNeIaOcZHw1DcAgUhZvbyFdV-mRjP84FRUpCg_dpBpc46u3Fc_RflJUtpmcRgCOJ11",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEPSLXvtnGAnrD2ealGGMSkoQ91PTEPaTugFjdYRxFvfhg81Y-EVmKcpnxNf15VvhqYnD2e_Ly_iQFUReCY--xNbtkirg7gtjMl2dkrsVsgbxsIDFPet_dJIy0j8VaBi488zAxBD112de0L3ZXD3NeQpd8="
      ],
      "search_queries_used": [
        "Freixenet Japan office",
        "Freixenet Tokyo subsidiary",
        "\u30d5\u30ec\u30b7\u30cd \u65e5\u672c \u6cd5\u4eba",
        "Freixenet Asia Pacific",
        "Freixenet company size",
        "Freixenet employee count",
        "Freixenet Japan news",
        "Freixenet Asia press release",
        "Freixenet Japan hiring",
        "Freixenet Japan Country Manager LinkedIn",
        "Freixenet Japan Marketing Manager LinkedIn",
        "Freixenet scandal",
        "Freixenet Mionetto Japan",
        "Freixenet ownership"
      ],
      "verification_gaps": [
        "Could not directly find specific LinkedIn profiles (name, role, URL) for key hiring managers or talent acquisition leads within Henkell Freixenet Japan or APAC from general web searches."
      ]
    },
    {
      "company_name": "Ficosa",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "A",
      "asia_tier_evidence": "Ficosa has a registered 'Japan Office' located in Yokohama, Kanagawa, with a physical address and phone number listed on its official 'Global Presence' page. Wikipedia also notes 'Ficosa Japan (Technical and Commercial Office)' established in 2001. While one source suggests a small local team of two employees in Japan, the sustained presence since 2001 and a dedicated office with contact details indicates a registered Japan entity with local staff.",
      "industry_primary": "Automotive and Auto Parts",
      "industry_weight": "Medium",
      "company_size": "Large",
      "employee_count_estimate": 9000,
      "why_it_fits": "Ficosa, a Spanish multinational, aligns with Wendy's profile due to its HQ in Spain, a rubric-approved geography. The company's established 'Japan Office' in Yokohama offers a direct in-scope presence for Wendy, who is a Japanese national based in Tokyo. While primarily an automotive components manufacturer, Ficosa is heavily invested in advanced technologies like ADAS and eMobility systems, which offers synergy with Wendy's ICT and B2B technology services experience. The recent repurchase of Panasonic's stake by the founding family, while indicating a shift, also presents potential for new strategic directions and commercial initiatives. Wendy's cross-functional background in marketing, operations, pricing, and supply chain within multinational environments, along with her business communication level Japanese, English, and native Spanish, positions her uniquely to bridge commercial and operational gaps, especially in a company with strong ties to both Spain and a long-standing presence in Japan. Her experience in B2B contexts across diverse industries is directly transferable to Ficosa's role as a Tier 1 supplier to major automotive OEMs.",
      "confidence": "Medium",
      "confidence_reason": "While Ficosa's HQ, Japan office, and industry fit are well-evidenced, the reported small number of local employees in Japan (2) and the very recent change in ownership structure introduce some uncertainty regarding the immediate depth of commercial opportunities and local hiring appetite in Tokyo for roles aligned with Wendy's profile. Specific recent Japan-based commercial hiring signals were not found.",
      "role_archetypes_likely": [
        "Business Development Manager APAC or Japan",
        "Sales Manager Japan (B2B contexts)",
        "Key Account Manager Japan / Asia",
        "Product Manager (commercial / category context)",
        "Pricing Manager / Revenue Manager",
        "Operations Manager Japan (commercial-leaning)"
      ],
      "flags": [
        "Soft disqualifier: Ficosa plans to cut 172 jobs at its Viladecavalls plant in Barcelona (HQ country), as of April 2026. This is not specific to the Tokyo office but indicates some restructuring at the company level.",
        "Limited local headcount in Japan (reported as 2 employees by one source) may imply a lean operation or remote roles primarily."
      ],
      "suggested_next_action": "Message Ignasi Claret, Chief Executive Officer \u2013 China (and implied APAC regional lead) at Ficosa, to understand the company's strategic priorities for the Japanese market post-Panasonic divestment and to inquire about potential commercial or business development roles. Wendy should find his LinkedIn profile for direct outreach, or alternatively, reach out to the Ficosa Japan office via their listed phone number: +81-80-2094-6953.",
      "sources": [
        "https://www.google.com/search?q=time+in+Tokyo,+JP",
        "https://www.google.com/search?q=time+in+Japan",
        "https://www.google.com/search?q=time+in+Spain",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE_nV7mU11q-KVb1Lo_p-TbinmaTimAfpgU8bt9cb0mEK1zs_wIyN9g9wmCVdj4fCmbuU2sylSFej8tuy7M2yhkzTcTO-2KxjSnGRmqrndnpUfVsbHD8DpAiToGdIodaA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEmKGNNXBsLVrT2BG_3AK3VIkv3DfseXs8ZB2PY9HuY2z7Ox7Ey-Th9hR-XOWQBamOL20sp_v8IQcESzio1t-iLSoM-ZRyW5wrL-KMuQpE4mEI13QoS7bgRY5MxGqu4hf5WZbickpDIIVUJmHzF",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHDZ_-tGJCfQ2GcCC13id8lIJo8xtoAOjg8OztKyRnalXHfCOY9fS5rn1gdXIWvHHAaLZmRwtgbB8zrd7Tik4vWZAuQRNXJkioNMuXX--j6KvupSkHvk_DuNF-QfNbz74u1mH7Frz4_HLsu",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFY_5ukZuc2qIBg7LbJp7yKqoG3TqLzZPAqkw_svgWtFrL52sWQYBv2bwAqJOSh6UmIP54TX5SeSEiqH_cQS9-byUkTm5KwWIg65lLxcEBXYCozUMqCzAP_VyBMunhbFYa3wtwwpN8Qu7gAwDwWNHAWZb_Qpl7rgoLMIoypSXLjTdlAvXz5kMEi-h7pG8S90eHiILUU5uqB6A==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHkupCxrnVTzgl9WuzEqYNzQW7GTNS0WHqGWaG3qbBUfR36Y6K5iTZMQofC73bdk65Pd7Byld2ZhBR9CWn1G1twFuJFuaf4D0Z5Zr-5HOpy1zXto5SuL00pLNIfvSZ82KxL0moQClAPpzBvvB5edFhp0HqHOwKahLJ2",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEHAngeJD_aBVftkLdv9kkHH2oZEUtd1t2FjiUKN7uTIQiAyzHiKra2wT6u5HegsR16YTbMARq8Hp_F6VQlSFEg0OQ8JarxORrwKZSyneIyZfATcMOv-0RB4ju7atM1yC18vLKGYHMrZZ0LwjtL-dkjVFbeT0e8_v2D6yGzQdMEbjmwI0NMaLBO2aqtlZht",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG8dDYqYybLuDa_9aH7vjR2Q3XjGwkM0vjmrNFsCqWq9gi5Q7f3ufEhLoyhaSXjuZKHjOkbheUddcOSIYsU2ZvBnl1keBfi44LdvoW_ln3Kcyf1tt21S4rb6H5ozlKmCx4YldA66AQ=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEnAgHD9IcZZrbEWQG8nlQJ0gXzM22xuQd1Rd6XjMN_RcvocCIxv73lJPk5A2r3aMprxgTGgE5Kyw6BYp94lx_1tcZBF8vBQ3ZeuemFGoTSIJndYZGB3HgVE4qIoVtdng==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHtj1MvbsiIItAkNQ3gz4GPeqAZoLOHjkvePNL75gIrveefKF9mBN96lmemw9U8VrHun2PCC6ZUk9IULe2vxi3LiJFI3jLP4f0owlqL3xDg4_V8QKuepGS2uiXoW8K23Tare2X3khcpG2BMUN-dV5qGp7o3",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGSXS0f7qvV_T3STMWpo60lbwpplsfMOxxMPvap4qRRNEsKtwcI3CSGzprULVP9Q3A-j9InZLqjq1Z_WDEKlhWtKNf65_9tD8vpFzHZeq26G3gHXsct_dhiWLYD3iFNuy6S1CsUKNtYZVT",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHB4fNm7ZIWKdUUjYMGpi53vhozV1Bk8sxCvnxn5LM812LwXumutlrLFdxmS_oNbpKTvnRiRKXqcrKJUTkMPnQ9_1DwmvqUzWe_reuJlrvO26SGR63K5JKayTCQoWVB4onhrq1oDK4GI2NOhQUSjrOS",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFwIFJZf9l3DosDg0FbUNr2JKcA7k9TIssBzn22AMx14YHGuP6Iymx7xxVoEQ86jDa5XQGZOCEtXKljMh5LwhYWOnVzqUCsGNQofMhWD5GBgf7ya1AC3OS4FDTKpbh3tx-8RbSUVNUZlElueU3NnjCLrR49RycKvUagUUZnM38cbhPLumOnUY0QMbP_LFEovGrkhNE=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG5q947LqekbJ74QBTKnqIF1l8PKooERI4URpSjATBaGtb_-asYeDbKPvz8DGN78QoCIssAGA1Z2TTPbP6PdTTerAga8ThuVBDu6mO-3BpAQfogjsthGz14P0n9r8b0CztDu_Arm6YesXUKXgFQCj0c",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHCJSC5gVHFmUUpwzzpVeb5xtUHfTjifOO7TT-VbN2Y5uilglf2iiVXbrDehEMhrvi9KTbgmmFJiAErhqp6T8mIS27A8n1BnjfAWU_FyCTUZSUwA0Lfb05lcTNa_MwpFsNo3O8HYOT6N5_mPofOcZIcEbadpYjO9sKRo6Qi5zt51RuUtLKrGQhvmw=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFZ37ITyj7ett0vifvw7azPwC8zARG_N1Qd4aPIC4miWjvBH3bwxG706S81of_mEprh_ude-nlrlWf2VQo1NR0ocTcRNvNta5zIwha5Jzi33mj2lbf6uPXGf-akBnPpfoLeIPpK7AzAbRHXT5IMaI_WxwmPGoAA9b1jO85y8B9JRqZbcOj7ZRm5Jlgk4jaTHhIGhUffuY17AwQVKWcVXgRRX2Dtd4yYoQcXC3xanBm3ofOV_RPd27RGPI_YZZEp7apugDA=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFBAFPyvcFeS69u2RjVBSQytRGRK4OZ3bUjCso_-L6QzN0GpymZQuQL3HGr7NkKvYofUzRHyRXcvnyEXXFfCk5F2yAeCVA_j3Y3j_QQsaQfkbqxu4a5Ok6ml76ZR1EB-GbHc7F-6Kjyd-186_euihZQO7o=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGEyDqWwmZXS56-2smULUw-BiGM-581au-HgmfqLS_cjR5TQk8POIsqATdp_9PCoxf1AePWoCYRyTa4gYEIAFW60AGn9OHVyAE8avuAMIUp5_77pUw_oVQYhTwhzjl6ioII_032EQ3Mqoez4O9d",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHf07dSydOo6P6j8pTjEWKCFzLZV4_vlKzeF_4PLBZLA5hC-aAIuhLWk9nfOnude369nPqD4ZVKLHinqCSxPoI4OrR-pEiy7oU1gA-yTR-VZLOtLR158dWUViAt7iuaU9oVq184r8BM5XADSprxar2hQpqAPN0=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEHcPYNXWvksMY5VfsSO0f7WNxBjdGUDmxtTCK_8alwWjb0kzOhgVJRn7uDPvqAheSftRKKZ2WrQuFy_J3bGTQ8VGuZ9wvl9TZLWgLi4tMQppaVCj5vUXRjm1TP1sWIdgYoYa4=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGL9oRXszjC5ScbppqO8iwSQXS6sNmWZSXuCaCWSVgMIeKUEp2qevtmstIsqjALkkFBrXD7FervX9V51tK807Iycaj_RRFlXLvPv04KqIKc3nKRkzKFT6Viy3i2avCZaRL3fwo=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEKBGhg04dBPxyo_f3qvwvYkTcxidtzZijUGUdFcPIO1Kb7H5YKGLDNp7anUEVKTFdTsuC0fuzhvPA2ZBxVzppx57NnPomW6XKzb2ghrjxa_67LpJDyzRwP_vDY5luXA97uuGQ9lovn0ov2ZchXmm429VU=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHGzruQMIufs4V0U4Vj_yRgUoW5GG95d41oE51Pv6Eg7l8r7KKvSuU7M0tJMwuHppY4-UtFVeFLwCidpq0pgBpUeFInfag59EWD_V4rFv7IxMlLG2TGwG9LGvIUm29fkKeWeh5cwLhpD9VqXTZyoSA7pBketCtQKvou-r_P98UwNU4Zpi6r4zaqZ5-DVdhCTsMb5G9WjvOwFOXekfDnTBTpFw0PjFELjp_cPyCC7j5-DZD0vAXDFxVNCuZJYwrjOoN",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGsVvafqwx9cyHQwXZjhnMsfFK0CTFwO4UWbO0VPoIDd33Nmq4kGSwhHluMbb333cxpIHOEu97u1gqGhJeOvwF3ep9UdjeJZASqh0e6IIGFuFaP7lWDHq6urQN_Eg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGvgmZS5NI-JSChwu45GMSNOsRufuBUsNW1p7bQ4cI8pijHEMUVVnXx2szLGiZltdDZ3WMJZ_2MEx68xmWT-9GdMsB7GkJ6wV0ylesKSLkkPaC_iXakX2ztuSbl3KjoB9lgtoZq6HcyC-SLZO7AQ_5cfzVfyGTH7oh8tSgbYhVaXXVx9pwUHk4lY3uri-sA2xhSjH-TrmAXkw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH49BT8cX94A1K4hB8yP5lVwOtq2GKNN2gjH-S2rJapD8Q-keqKZcAjX0myLSIgUf-9mr-r5iVh6JMM__mpL8cHUehujY9PNuq8cePVHLd-bCCFEEB0yi9AN_sGTqf8VAcvnA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF1l1HlKl7ie_4AFnbp4jaAfPOFmZGVvphSrgzAS8cyjSNOrnhHH0sxMKWJsSMj50Kp9RXZLF-H7WS1y8DhREZlcw9ZRXwGMZBBZhP2gkCc44iu_-eF2X_1oPZx_2w1SROGgxejeJxufYOTs1HJLPrwd663jytQQINd0acRq7NEIBai",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHXWjyvxyJ4w1XRbZUz8UdDiaaNMnVhF5mmX8FXcrzSgSEhKiEukgGION0mm9cCbAyRwisUFDk5c6Fu0xXaE72wF0rsf89v9jKy_zCgGjNH4ctyvWyuJyGCjmnrJ_vJfnaPGOys9UftKQ="
      ],
      "search_queries_used": [
        "Ficosa headquarters",
        "Ficosa Japan office",
        "Ficosa Tokyo subsidiary",
        "Ficosa Asia Pacific operations",
        "Ficosa employee count",
        "Ficosa recent news Japan Asia",
        "Ficosa Japan LinkedIn",
        "Ficosa Automotive components manufacturer Spain",
        "Ficosa Japan LinkedIn employees",
        "Ficosa Asia Pacific LinkedIn leadership",
        "Ficosa talent acquisition LinkedIn",
        "Ignasi Claret Ficosa LinkedIn"
      ],
      "verification_gaps": [
        "Could not find specific open commercial roles in Ficosa's Japan office.",
        "Could not obtain a direct LinkedIn URL for key personnel like Ignasi Claret, CEO China."
      ]
    },
    {
      "company_name": "Codorniu",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": "",
      "asia_tier": "A",
      "asia_tier_evidence": "Codorniu, as part of Ravent\u00f3s Codorn\u00edu Group, has a dedicated Japanese website ('\u30b3\u30c9\u30eb\u30cb\u30a6\u30fb\u30b8\u30e3\u30d1\u30f3') launched in April 2022, featuring Japan-exclusive products and local PR activities, such as a wine bar event in October 2023. The company explicitly stated its investment in 'offices in Singapore, Japan and China', and is listed as a Catalan company 'settled in Japan' by Catalonia Trade & Investment. Furthermore, Codorniu Asia Pte Ltd is registered in Singapore and focuses on brand marketing and promotion.",
      "industry_primary": "Wine, Spirits, Beverages",
      "industry_weight": "High",
      "company_size": "Mid",
      "employee_count_estimate": 600,
      "why_it_fits": "Codorniu, a historic Spanish cava producer, presents a strong fit for Wendy due to its direct presence and significant investment in the Japanese market. The company operates a dedicated Japanese website with Japan-exclusive products and engages in recent local promotional events, such as a wine bar in October 2023. Japan is a crucial market for Codorniu, ranking as its fourth largest by volume and fifth by value, with a positive outlook for continued growth. Wendy's robust background in B2B marketing, cross-functional coordination, and managing targeted marketing campaigns aligns well with Codorniu's strategy to expand its premium brands in the Asian region. Her business-proficient Japanese (JLPT N2) and native Spanish language skills are highly valuable for facilitating communication between the Spanish headquarters and the Japanese market, and for leading commercial initiatives. Her diverse commercial experience across multinational environments also makes her adaptable to Codorniu's global operations, which include an Asia Pacific hub in Singapore.",
      "confidence": "High",
      "confidence_reason": "There is strong, consistent evidence confirming Codorniu's HQ in Spain, its Tier A Asia presence (including direct Japan operations and a Singapore APAC hub), industry classification, and company size. Recent news from late 2023 and early 2024 further corroborates ongoing activity and growth in Japan and Asia. No disqualifying signals were found.",
      "role_archetypes_likely": [
        "Trade Marketing Manager / Specialist (Asia, APAC, Japan)",
        "Marketing Manager Japan / APAC",
        "Business Development Manager APAC or Japan",
        "Key Account Manager Japan / Asia"
      ],
      "flags": [],
      "suggested_next_action": "Message Maria Vidal Tom\u00e1s, Director of Communication and Sustainability at Ravent\u00f3s Codorn\u00edu (search 'Maria Vidal Tom\u00e1s Ravent\u00f3s Codorn\u00edu LinkedIn').",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGBCBxZ5ROwHeCjp7U3DeupyngxvUgxGKLT_IorZ14RXxrdlLcULQlobeuFGft-aeIt1a8oSbm7HtQJcjIWj9_4zCF0f0EXdxeXyD4a8C1IGuLrR1CtvBedxgMdDbMbUeOSvFEexyan-iA",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGjCVUX9juZvYdY3QmhuhhYWrkd6iXylSTfODhjvmHAAQkK5Ln3GtzPMN6BNyF-dEmMNfnfUNV-oIOUEi_bihcIEzGhln93eDQLjqe024_8pkiMTjXWYMcTI4FbB2EfRNoxK9b8Kqc87rzYwJhS",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGisCmutoOySL3sRbT_9M9KEw41sBRId_a7oyMIwVl4GdyX3QwKtg1tVIrCNutfjz_24AikBWRDyjYRf0cWJ7cbwMz5LgO5GIxl5yxpwWutNSdU0mCsna17",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGMzm7oHOkfL_mFlewtoJPXRShH6ngH15R7vcU3MIb4fAGSqkCvQ_swIKe8VtJgRJP-DARE2_hWifCUav_9NVNo3Xrwv_RmxCDDhfhXyKtzuoC6XTmxeAd2tEeZ08--VupdqyJcWUt9Q0-Vsg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFyctVC8zYx1NIKhsjvrwAL4UJMypXKvjtmG_Po54BU3ElpnGdq4EhGhKm9owmJ604hz9ircgWiT17b81agYPQyGRb4HuTjFQZqf9gTzgqtKbzoFXQ74ztzFCZSgRxnY-Ji4CbKdHh65gfUqBjUXeWLUhqpR7TPD6_wQXiE31ASmGg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFOHVHMnbmpAENWtOOhfEeAsCdJQHezRMNVnrberND6XfQZ7f1nQ5IIam7peFfci-Y3Eysu8EkAabtuvUs7TLwZnLfY5uhUA6OU81PI6f4U2fT-sZDQ4x-0f2Az6mrYfhI4vsdn8jH300H3vJoRIO5OgP4n5rncIUxwpTUt9g==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG2M0ygGYwJbT4UJgVywGiNWyCBFI8QVRTsMvS1we4XPQycXxEL8yNPRMfMscAwfMoCaCgnMZ4XH4C-86g8zd5IvU3AnTTPvEn_NnezpnNNIWrqrtFnn_HoHrsgbnbuD5_SR7wIK7f5HtUCmU0AlowpBab1zQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGpE208A4KJKkkYBLSFPMaMqJ_aaHQE05ALGKVChpW-o_Lkf65tHHZNTmixHBfciU_B3-BU0-NUkN4ExckUTGGW3-BI6NnctrbRqmKcSZfxGJ20_w==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF1cQYcA0WRdql9zQ8F6SjmTbzn2-cVPVEe4eEOfsdOrA-AceQz2clhEIUmmN30S5OS9e_XgMA_E8NzpBombm4EScatbr6xLkuP5AH6huvmtIwtjg5FBNA1hvQE3KK3k7fe7eswCSFVAG9JdRP8ZA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFHBesXWFvzSaYKG8Za6U3n8k8KsV97XRIjhMBaS366Ig0lOsYioRGNVtb6xj32d3zirNf-_0DKtfX5T_BJ44ZHBEWgzJ7-PLoRYfeODNTk2NddWxnRO4QtE1k7Th5rZfbZFmQyJZWw2Rni",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGP6KqDb2Bem89OHFTAAwHuakLClXUoxBZv86k5r_IeqRF6e4LZ7nFBTAKr8S2GaQ_jm5Tc1zEdxjVUd3u2nUUErb2buppi5FjG3KachFsWS38BE3coG2IS5Qvn1vF8RESmNDN5sdDljn69DzI4pcOYgjXcD0OR4fs10gNlAYFiGW2yPXLYkcIhS6mR",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHLfjYynj9BPfIaHkzvnqEbY9hJ6ivz8cRh8Dw0Lb945VHIjbjEhRyuWpZYeFE5DNlYx1nsTsh5Dfjxj2rgHkYWo2DjByWbGf6e9HzC_Fdw9HqXLFIcFTnOr-aAxm7ND7pkfBMzWyItjlNlPDEXoxDdwg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGlml0Zw0Sk_-QpewAbVTWeR5QfefaRD7ecp0UIuHoMcPz-ub-0VrjEgEzn4Bx0Xez4Fs017E9CUK3qzp1qRP9CYU95YDDTKmVytcmgyeARPZGEATQ7nLgk7y7Q-YDALIXhsyUKwFQNZlLOf4vXejbrCovDncIcxSXw75sewpXj2AHcBOwj0i-c7PjX27SgUuNAOdbif0HP4gZcHzstjUF0CmoZYv4lS5g6FgfiVugOEA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHgz8IwwHW3nKPR18jiVn4Yt-4mqx8O7-A9rUVS8xAXARF3mXerV1TOFHTl7lpS2vIhcczq2IqdIH9UVl_jFlVP0P4xfV9uyECBgl53WWnVHvUIwH2X08k-B3R_kVrizAFIVL1XT6bS8mz_Df6oCgCE2gWy-I3wKFjP7QlmLtwGhXb-GBP5q09DUzk=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE77FSV11Ha2kSqGo1hSsk8YVW1W03jyxBZbW4mW6WJiUBlU9hXIp5AguAbebK5872nPKrP9ShHv-e2-O56JV5NhZHdooMnvBGO2NMJjcWdbje9hm2SVX0cnyE6r2q-48k1cq8ipjZb-OrGwSPyeqhh0pRhFgxpaQnAQG9GSpVx3AtAyfNsCobmr1psfZVgxn9p3eZAUjS6Gw7yN2Om9N54XciX6si_DXR9DWvCpc4V7Mivf14GLGxDu4XvonDzkGn1JST2zg2bNI6JlevO-t2n-dnOvRti0vpMeHRKiuphJHKQXn1wmF0SIUl6CyTonPmrI6ImpC5ewR0",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG9fqY27OViNE-GFmvz7nhQKRkDyyNCMUx3zjaH6Vqn4RRC1ZpHSAqTAK1--jF03kJujXc9yDquzw0aiC9v0ZdVqoebvmHxUn612-vrvnhP_fnOWmv4M34GTKzrse4YT8h1FTn7MY-lV3LWfZSdAfVI_4OPcmHV6Tw3k5CBFXrX7eew5USTJFk_oqiflqZcOEEIVigFzDAapg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF8O9U-I6DjRDdwnS_shgGkU6PAYSdmF1YG9o0YKo0ZChqMNKibztVzAZWbHuWjj1RLmT3Zf1T_zrPLaau6lBYVSbvVKy44-pWHRnRpuGpRsmQ32dSBFEQjH-_sboGdhgz7CcBULCqmnnhHMvNT5dds5AdFqH656K7DczWULSkoqdz0xpVZ3DfTIrpmxg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHGbl94LTFKMpavyutQc6YfTpAnHfqkrE-eyzsNfqGPd61n5bdUXtrjizWZrN53MTA_yLHBgBbzFz4o5ZkfBcu0KQlLLz0xB9UBM1wnOvlNyItEy26sNzDxp7toG7LBlBWCKcfFtPwqW7bi8qGSMEzaVATKE546afzCvWuxO_0SwtL6IeodHB1Rq2dhLsJW4WdReW4=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHn74rV4k7shsWwU-fvY1tslvjptfxmLPgJr4J6yq3OCmvRNwxujIm3n0iZ_cd4Tb-vnJrWbE61iG2QHEnwMuudhBYNDh4JeXArvritnllqFi_OlddgGd4Os487_R-Y8Vo92_zlwSQGYyIY4IDEs3r0zM6rAik2JQn3ZLZG-p1sVwbMB9twnII9xZI5hTqOYomfe48Ov1fX0OFCcqOTZ-apGDijUL30hB6O6PM="
      ],
      "search_queries_used": [
        "Codorniu Japan office",
        "Codorniu Tokyo subsidiary",
        "Codorniu Asia Pacific",
        "Codorniu Singapore office",
        "Codorniu employee count",
        "Codorniu LinkedIn",
        "Codorniu Japan news",
        "Codorniu Asia news",
        "Codorniu press release Japan",
        "Codorniu Japan country manager LinkedIn",
        "Codorniu Asia marketing LinkedIn",
        "Codorniu scandal",
        "Codorniu downsizing",
        "Codorniu company overview",
        "Sergio Fuster Ravent\u00f3s Codorn\u00edu LinkedIn",
        "Maria Vidal Tom\u00e1s Ravent\u00f3s Codorn\u00edu LinkedIn",
        "Ravent\u00f3s Codorn\u00edu LinkedIn profile",
        "Codorniu Japan careers LinkedIn"
      ],
      "verification_gaps": [
        "Direct LinkedIn URL for a specific key commercial or marketing contact at Codorniu or Ravent\u00f3s Codorn\u00edu in Japan or APAC was not explicitly found in search snippets."
      ]
    },
    {
      "company_name": "Tous",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "A",
      "asia_tier_evidence": "Tous has an active, registered entity in Japan, evidenced by their official Japanese online store and a physical office address in Minato-ku, Tokyo, with a local contact number. The brand expanded to Japan in the 1990s, indicating a long-standing local presence.",
      "industry_primary": "Retail (Jewelry, Accessories, Fashion)",
      "industry_weight": "High",
      "company_size": "Mid",
      "employee_count_estimate": 4000,
      "why_it_fits": "Tous, a Spanish jewelry and accessories retailer, presents a strong fit for Wendy due to its direct relevance to her 'Retail, home improvement, consumer durables' high-weight industry experience. Her background in B2B, cross-functional coordination, and marketing aligns well with the demands of an international retail brand expanding and operating in diverse markets like Japan. Tous's sustained presence in Japan since the 1990s and active Japanese online store indicate a mature operation that would benefit from Wendy's experience in supporting strategic marketing initiatives and data-driven decision-making, as demonstrated at Fujitsu. Her conversational Portuguese and native Spanish skills, combined with business-level Japanese (JLPT N2), position her as a valuable bilingual-bridge asset for a Spanish-headquartered company operating in the Japanese market.",
      "confidence": "Medium",
      "confidence_reason": "High confidence on HQ country, industry, and Japan presence (Tier A). Medium confidence on company size due to varying employee count estimates, but all fall within the 'Mid' category. Lower confidence on recent specific Japan-focused growth signals and identifying specific key contacts, as direct evidence for these was limited in the search results.",
      "role_archetypes_likely": [
        "Marketing Manager Japan / APAC",
        "Commercial Manager / Country Manager Japan",
        "Business Development Manager APAC or Japan",
        "Product Manager (commercial / category context)"
      ],
      "flags": [],
      "suggested_next_action": "Search LinkedIn for 'Tous Japan Country Manager' or 'Tous Japan Marketing Manager' to identify specific individuals for outreach. If no direct contact is found, identify the Head of Talent Acquisition or HR for Tous globally or in APAC.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFDobb8j8LJ0iKvL_l46nfTs8WIi8N149utKDpWp_VRqEh0REW0gbl-jwal6oh-78ycbbzkHZik7waMxyIlxkHjKzfWn5OdRhAKs8xcA7D7Ck7DZbtg-inXFCfifka3TgI75T1QTN5W",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFMDHMFX2KZQC1us6ynUBpBsBP58f29mCG9wJ0sGoYwNfda7t_NCtnMEL2sDo1Wjl1bhL5zODlnmUsJ4rxWdQ2-eI_7QI8ZVLBZK0U6fo3ubsQ7ZZ0Dl92NtV6tIwowlM-yhhtqE0N5heXCtOdTHzR33uvkPRzEOpCDDG8GIc6YJwGDyuY7ENUIuxK3Lw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGbH5_2pfiudodav7LXWqCmMucgLwAnKArcH29AjcLr0HpLtH03fFOVU6ptPTurjCMGyN8dmPEjj6DqeyT_XO0EtWRJvFrFDKSQFM_Y-zGe-hDxo0wTC3ZVFBe_o5azrgK8PBVX-xR4SOXH",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHmdP3k8Zqrx-IMxgiW7ozaey3vNdwL4bHl_SL-I2fcA68Tz1OLkO_Uj6O0cQllXH1ebWko_4ao1Z-NMpMcYJNPvyuXHHlRl4w_vFHZ_iScwWpvtUjytplFvmDKfpfxS4p2JllSWgoy-fuAmndgrs1__pyORQTnijkO2cJTieYKOzw4sNE1U0YwDy58r9mBufpQ2gS4V7xVCUxO543gtSc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGAEFWVJNaH3Kq8y7CzyftHh3Al0JPrY0Ur420l0Iy5FdzRGviZd_KXefHlEB-EPu8WDP09FQ_7JZm9EQg4uZdg6G9VJlRxUGheIkgl_BZDWZxR0hfeqTbXeMU21JUjZjXwu70mNApmHNccz2nAcVS4VLW7bE1_uq_5mUA4nvxBCdurJ57Nbi3F-UL-kJBg-dFH4awvptjC",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFq0sQ51Uxm9W5imVExZzpV_oMTbGIqQT-fvdiP62j_BUarkRm_Hx84QPYdX52FkyAIsGtBxqQ5RPBbjlWNFgc9bBFFpp67qDoHrxVTK2n3TfPcEDLXDeAEmvEqHmvOmHc3Qe5H0x2_0hXRgIbCv3zKhjalA8TFQFN-Hu0eJ2nOC08ijQPWzB7wXaVZknHdmDV-spjEOanSDwtPtNTbj-3rZEFTfHZHl96z1JXvmQcm",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFzkqAlkFvac6J5EJ9N6p8kk95ojgPOPHR3i85sMRICbUONTCPibcsuWJZ8qNJvRBwLPNUEDr4Kr0VB6Aazs_9FLYsXrDrJ_WYYxpr8tpLkpWi-MR_Jv4z_-dpb3UPF_lxmHKN8N_nN567w3g==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFy7ccVKTCxEzGN7c0juP80F5xMa9wVWH68oozoWS6CVEyJ2iwmIlGvzmj-I2PZZuaq9zEC3eGPvA_tmCKYqCoTulmcWRDQfhwQFEvSrpW_Wgj15xMpxtjC",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEY7N4ceQz05jypYM2FjfFTTYjoXePaWwzUjh3MeGzTzsLcbLVNVgNxYhDR1in5jS1yjslt-HGiaCQkKV23Xd7iOkBTlpvc_cHqwUh35_P3pjPyP05ayLgFTnU0QMKcZycAonkJ0IDwNdno-Agqlrkzj-K66nDEEIidMhU=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHRL41mhd4_ooR3BPD2gxrYiwJVXpKeJVnOQSX6RXGXtinPmSm45I5-xsN4FthlEpA7qs7amhIWMheuLoC0lKCt077SERPdQLf16tRDHLj6dujN3Z_D1CgfZr0WgU7gERfwNLfEWcJ1UtuW_ARKeg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF0zKynfoodiqV1aMqTLCf_jHO0xBuT2Jg9x1QQ39LWat3T75k-8h9Vi7hn1qpaTcIvFSYu-2nfJaM3AE9E12aAXIYQ60qN2xEaEpNYJXAbOfaef9eZmf71ejAiBA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEACNLUL5u0kuuFYWMDT6qgjay8wI4rVv0bHntLbESeKxza-1Kxuggsi5lubBZ7ZHqSMSLNMb105s3-AnYT_29D1r1EgJ4OI74ZAY3rNCv4v148nuaD1g==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHrGRu329GD0nBSo4px8gUtpH178jGnPyEBn7Vi7kPzqE7yQUxdqrdQa4crTWouvmqVzgky2XxV-iXEi7cN6H7o4CQTKFPN1gTLzEdJfARa9CVHVk6-FneyLkK-Pdjid_K5tiCtq3Rjvt1yZ9FX",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGO_IFaTpm6zhPdc16_cGqItzqcotrjkOI_77Q_ookSFYGHsxWSaVP_YUdBtAidIRsEnr8X-noJy8INsAoFZRQJ_gFzMfE2gqFbqKK4teY0Dj6H7c0lKHCI4sXqLQ9Bbaw="
      ],
      "search_queries_used": [
        "Tous Japan office",
        "Tous Tokyo subsidiary",
        "Tous Japan LinkedIn",
        "Tous Asia Pacific office",
        "Tous employee count",
        "Tous news Japan",
        "Tous Japan careers",
        "Tous Japan country manager LinkedIn",
        "Tous scandal",
        "Tous company profile"
      ],
      "verification_gaps": [
        "Specific recent (last 12 months) growth or expansion signals for Tous in Japan beyond continued operations.",
        "Named key contacts (Hiring Managers, Talent Acquisition leads, Country Managers) for Tous in Japan or APAC on public platforms like LinkedIn."
      ]
    },
    {
      "company_name": "Campofrio",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "C",
      "asia_tier_evidence": "Campofrio Food Group exited Latin American and Asian markets in 2001 to focus on European growth, selling its share of a Philippine joint venture. However, its fresh meat unit, Campofr\u00edo Frescos (part of parent company Sigma), actively participates in Asian trade shows like SIAL in Shanghai (May 2024), with 60% of its annual export volume destined for Asia, mainly China. The company's products are also noted to be available in Japan through distribution channels, indicating an active commercial presence rather than a direct entity.",
      "industry_primary": "Food, agribusiness, protein, beverages",
      "industry_weight": "High",
      "company_size": "Large",
      "employee_count_estimate": 7000,
      "why_it_fits": "Campofrio, a prominent Spanish multinational food company, aligns with Wendy's profile due to its HQ in Spain and its core industry of food processing, specifically meat products, which is a high-weight industry for her. While Campofrio previously exited direct Asian operations, recent signals, such as its fresh meat unit's participation in Asian trade shows and significant export volume to the region, indicate a renewed commercial focus on Asia, particularly China. This export-led growth strategy, coupled with existing distribution channels in Japan, presents an opportunity for Wendy. Her commercial and data-driven background, including experience in cross-functional coordination, marketing campaigns, and B2B sales across diverse industries, would be highly valuable in developing and expanding these commercial relationships in the Japanese market. Her business-level Japanese proficiency, combined with native Spanish, positions her uniquely to bridge communication and cultural gaps for a Spanish company looking to strengthen its Asian presence through exports and partnerships.",
      "confidence": "Medium",
      "confidence_reason": "While the HQ country, industry, and company size are well-supported by multiple recent sources, the 'Asia Tier' is a C due to explicit past exit from Asian markets and current presence primarily through exports and distribution rather than a direct entity or regional hub in Japan. Specific contact information for Asia/Japan roles is also not readily available.",
      "role_archetypes_likely": [
        "Trade Marketing Manager / Specialist (Asia, APAC, Japan)",
        "Business Development Manager APAC or Japan",
        "Key Account Manager Japan / Asia",
        "Partnership Manager / Alliance Manager APAC"
      ],
      "flags": [],
      "suggested_next_action": "Search LinkedIn for 'Ricardo Est\u00e9fano', 'Director de Nuevos Negocios de Campofr\u00edo Frescos' and message him to understand their Asia strategy and potential future roles. If not found, look for international sales or export managers at Campofrio Food Group or Sigma Alimentos on LinkedIn.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHvQgiZ4WFhqskbTa374fNXp3pYHxDowvG11DgjksnmE4n2KFsRAehzHPjjEZDBbi-AFXMC_nOtYOiug1Adq7up8o8H5k088JWeUGvKpEH1jHlTKAsLWT_Wp907ifx8ArTy9HHWpa_jZ3O8WVFja0I8ww",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE18ucGJNr524UPHJs_BvJjdiIxCJocJNGEnEOMiAQLWyxUzMjMyM8WpTzrZSDeWEVIS2QpRiwz71WIcgO2iZtmoNs0uNZnKw0_tVuNx2x5oRy382bLQJT17xKiVQ6cAKudXXj6FNXgY-w",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGXEF4c1H44KFqAVrIEy3ongA6DX_vuC-ZZAJZug89VL0pcByVzfUOIqfnpUuFydLt5Ac762o132Um7vO_ehmnVQQRgu-jwYshRDcnZ9vit2NBx2ZVoRg6fdixAhxeTG7FReliGEoX0ZGMqYyy1W_8QaVh3GoEbgkRdWzm4lWIZrDlSsuqMLeA8KOTdBJ3WOAu8SOGlWw",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEGfYABr2pkatoGVqn6tHupGgPxz2N7a35k0t_X-kimv7wjooOkrSnFP52FAPxT9y9E9hS9MSY-X1fivbD85Ew8fShjaWHYycHHY5Ga59Hnvt9hmaveXAKaLZKpro1vVk7bJDOOUWWXPDU",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFbZxV2DCAFTJ_YSCGzrLkHBCyGdYZqIPFnHokwMHUjC6seRtUDLydWmpL_nNoDRpDyCEa3WW_pQphnx52OJ4yVp_7KSJhXHqyGbNWLorLThHYf68uoaySjnNiWXgVegKYEW3aiuHOeGfUVNEmUWtnXauXRPiJCxI8hQbw1XGK2GlieURR0QhygxZpo_V0S6c3x",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQENC8uYC6XbgXEt00OUuWGqkBcrLSaEeIApT_mQuP2krdTosUeg2EGtbQm7Y14AtiVTd-goT8UObMYtgXFxoW-hCkDwiBGbpGOQqpHpmd0jK8hSEzifob94hrwsyrdC7X-ijfG6-lKCcW3ijA",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH2YplWa3LMs_gEaiq8UhYajK8vP8F4Oz3aoTmUj0Qney924qhZFD22IBzblJbMIThwfVIXlPQaPbJ2G8w5XmWWz5UEFHVVb_iqQaDJMZq2fW8AskN5YqUIWXGttAk2_hJQ2l49WUohcmRdvLVDFwGJJw",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH1PDlvzTp28SET-vRc4KbATUKKC-9vXQQmn1ZHoyPD7w8IZRWRz3vhLA_UudTFxsRNXp8Gs_U9N8Z9INB7ODClqWMUM496q_h5ZT_cijBHpjoMIq33jIgFWTmqcA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFTqoE6ZxOhULlGCOqL73400EnVGTspf471ZHMQcVVrKuUE_nY3ONG_BLIEyQgUNdrLGZeH2Vv9Q-5cn5gi4kGCm4AYUUCXE6xRzpGGKXu_ptWsL4cm_f1TAfRJp7tSw6mkqMxGv-VQITxb_ETXV9rIZZ4gXfl2HJSfwFlIy7CdE3V6_bs=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGEb78aAUdxnWQFBb-Xr3wyi96W8hyL5JlymyEUoFR20x1d9KUXIyJvhmNyvnDpvW2Rgz566mcqUJC9BCacyPmXuAlT-y0YUccFGlUu5Qh4iZ8WZCIhr-yabQnQhDlWdWvO8Scr3LRxgTJXBpiuOK-rYctz2YHyuxFCYeUM9sJb77htvOJxKwzGlbWi3VzgJNOVaoJKqmitUcFD8yEHta2G_Ee_rKp8_Jk=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE1IAv9merfaDzkN7aoKdXU9qCpQB9TPpyG826FmMo2QUaubRdXkAkacdc09OO44XtPEKKotpC4Jg24DXB7nmdvWFczgtVkDbJZQ1zLS24Ve_AkG44hm_CYcArh0VpbNV_-JuBA422pzAfw_aMxJpG1yHvNW41SmT_04EB5nPjPaXhd6yR7T30K8LBvnXxJt079Yqstlg5se5OB1UAypBs9Tljclz-ykpvfh1Xnsrod3Wug9P0Ss2aTnCkzlg="
      ],
      "search_queries_used": [
        "Campofrio HQ country",
        "Campofrio Japan office",
        "Campofrio Tokyo subsidiary",
        "Campofrio Asia Pacific",
        "Campofrio Singapore office",
        "Campofrio employee count",
        "Campofrio LinkedIn",
        "Campofrio Japan news",
        "Campofrio Asia expansion",
        "Campofrio Japan hiring",
        "Campofrio scandal",
        "Campofrio downsizing Japan"
      ],
      "verification_gaps": [
        "Direct evidence of a registered Japan entity or local Campofrio staff in Japan.",
        "Specific LinkedIn profiles for Country Manager or Talent Acquisition leads for Campofrio's operations related to Japan/Asia."
      ]
    }
  ]
};