const dashboardData = {
  "run_metadata": {
    "run_id": "2026-05-12-run",
    "run_date": "2026-05-12",
    "companies_investigated": 13,
    "companies_excluded": 5
  },
  "evaluations": [
    {
      "company_name": "PAL Robotics",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "C",
      "asia_tier_evidence": "PAL Robotics has no registered entity or regional hub in Japan or APAC. However, they are actively exploring the Japanese market, having participated in the Spanish Technological Delegation to Japan in 2025, and debuting at the International Robot Exhibition (iREX 2025) in Tokyo to build partnerships. They also participated in other significant robotics events in Seoul (CoRL 2025, Humanoids 2025) and Singapore (ROSCon 2025) with a stated commitment to expanding their presence and collaborations in Asia.",
      "industry_primary": "ICT, Enterprise Software, B2B Technology Services",
      "industry_weight": "High",
      "company_size": "Mid",
      "employee_count_estimate": 150,
      "why_it_fits": "PAL Robotics, a Barcelona-based company, is an excellent fit due to its Spanish headquarters, aligning with Wendy's native language proficiency and cultural background. The company is in an active phase of exploring and expanding into the Japanese and broader Asian markets, as evidenced by their participation in the Spanish Technological Delegation to Japan in 2025 and their debut at iREX 2025 in Tokyo, explicitly seeking partnerships. This signals potential for 'first Japan hire' or regional roles covering Japan. Wendy's extensive B2B, cross-functional, and multi-industry commercial experience in logistics, retail, and ICT is highly relevant to PAL Robotics' focus on providing service robotics solutions across diverse sectors such as retail, logistics, healthcare, and manufacturing. Her proven ability to bridge strategy and execution would be valuable in a growing market like Japan, where local market understanding and commercial acumen are critical for technology adoption and partnership development.",
      "confidence": "Medium",
      "confidence_reason": "While there is strong evidence of PAL Robotics' active exploration and presence at major industry events in Japan and Asia, a dedicated Japan office or specific Japan-based commercial job postings are not yet explicitly found. The employee count varies across sources, leading to an estimated range rather than a precise figure.",
      "role_archetypes_likely": [
        "Business Development Manager APAC or Japan",
        "Commercial Manager / Country Manager Japan",
        "Partnership Manager / Alliance Manager APAC",
        "Project Manager (commercial transformation projects)"
      ],
      "flags": [],
      "suggested_next_action": "Message Francesco Ferro, CEO at PAL Robotics, on LinkedIn. [LinkedIn URL: https://www.linkedin.com/in/francesco-ferro-a6a8497/]",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHEp-sfDUGfrQZGXa1cpwU2p63O5jP9SWju4KamHQszPsLS4vUdEd9fU7RExxjL1BMBffFhvPEOEjZMIk5ppxA8_3wQiPW7RAVqulofafuz-vcx2YO6kD0-k5OSnh_PgGW3bpK7lQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGx-3bbBydNqghsMW2p4w_g8vMAwViCSN00O8hDABZQ8tSC0k53PrlknfbPXOHee0AC0Q8B18cXF4i17UPHEnJKxbXZfbWQOIYO919xditF7OyFtKSvaRSGBFpAIAFBe57jB3OpGXjBU5FoV6jxTrJPVNBvOSAgEeA3G18Sa-bL3MlL9qrudwuF",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGVflm7etaPIb_N6lGlFipjHR7QyDmqCK9qaW6jAukCYpz2Da0FwNjcktj7TlQLkqLe7Z4lDECIaLajFZ6MBVMNO14QDQSMXBuHCQLM4SeIRMKwVIT4Ss1POilJ2qGwhoEj6cfL",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHsAHk-KqtIVy_VjmBH8LCbRSkcjGbfKnkLeUt0pGqMU2Uzw6esh9udTar8n0SeTeW0CUT2wI7aeuEZCvWL_owCE7zL28rS5m9Y_PW2FDo90BZ0hu0_ii_oFrj20PaVhJAR4w==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEX8KMz4O53klWeC0gDTdWpsIR1AaFqM72wgFxQlKr-SuLNW_MaehQF4erKY1dvxqVqZdgjUuJht1NnGxfGx6OpbUWwSArVpkwDcF6sHSi03CegJshiBO-FHaZ4joPZO4D0PMIEacJrDiZbtibYH_QbzK1FFee0UG4ghAgRX1YDbFB6_9m7mHWXMgtEiCF60ev8VCMU_XOuzry73JxWtHNPY-SnE50=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFpRwomRX7u4Tdu2W5xCJZF8DCz-73j_EVYLd2Si9-F8-NdpXyDbSFzJeLxvxsYE7X5de49KGgz7sisVpjosb1pkD_PlW9mofipRXLUN75A9Yyl37PJu8pU2QMC7fXT-_jRF2s=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHd32uO5EiOgsaJCek7f-Ydo9LvK9DPgK3NabdSpQlEF64OpI9vpezSn2LuczgmfRH2mcV9ioRadkxapiCuNo-hV_ylt4BREGpQ1NvSOZpbJ2KKItu26C2ChjJbAGLwyA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHGrH65d59sEz3gUdhjSbsOrtwMGzdU6fKMl4nUe2m118ZKli3H9QqYNMdwpPtuog3mE2XrCvVr32-6oCUMWeANf_R9DD6xCeynO7H2azTaRZ7MgkndABTsDjTmfk78lYgzEQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFAqpFLHlMJ8S1leuzL2-ys57IwTxyTmSDcxP4z5GetXpu32wobEgcUwOV-SBdGW6pvq2zEZNpKvT5RyITyPWSwqLUXBjbfcMVQsR19Il5FJBLU-4MDmVdmIa3oo4YxE-cpKrU4PbWQ",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQICWcSpvwRhUZZaCqlms1YpGfDwfNBnYBt_DIc5409pRHUXNe8OcTZJMCRM6KeC3C865b-TJLdzMFM8ZTAfQAmqb3OBfz0Xt6rkF0Kn-kCtVIkvotZpIp_RZYX3ASrEg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHMhHDxPTqAJt3hZlXm9RLe2B5z6AnOM5kIEyoNslBlXWRYIeaB8ZRzIBnYjeC9vqyROeWPqSWmoS2HQyiv6KHA2-mYzBEz7AnQ8bTJkv4aaTu8ERwfE4GviL5pqUAAZ7_skg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHZDupu5FhJVK6Caqrs2pdVWsSjvT-K37s3umxWWVoRx14GIFTi3WlL33_B_-EeCodPukCqObU7ZSoQ74pKpWJwUKtlVgfO8F6ztCftWDhHvRUl9_pHdwbSAfkmBXCXas2ncnD0iGoL",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEt-9h3TAV-FnFrPHpM3sq3X6HagH5B8rMOpvnCOmJ1QXWzHJ4cC3eZEo6lKGXsDuUSTXEDQw4EGqEVHCRQomDxenDR91StnKnNHSmNfqwOnISjbsM=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHAeK0A8cEHJoEZb-5nFQukCfEXu_gAoQpQUeWuc9YgpTZx7kYPqzp6Dk2G-_KRkzA55R7_bnZswIEdx98zbqp4pnDNNUan4-k_S2jTtDEBGhUmH9f-VLjcu80_EA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGYcwIk8eDt74d3k2MK_jA9b6qbu1QZt5djaJVHsQ_nDMWmiQDXU0UjfNFEqQ9VdKcMf4YaLSvu0rIEoM-3eDvCHfJ_nEy_Wj2PJ-0bW6n7qT918lUuhx0DtzoSa7Jt684LPP13Msk=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFQp-RMmy9oz0n_xrctCF282aM7YnaCgjH4hPNRO2J45zHazVZT06NxnjcU61xg6g-aDXZe8IJ04g57BQvyDmj8ZWIDhRKGpcSL-e2hxEp7rx5ojE7cMT26aSg=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF6E-FsXaG1erkWQ-VWi5yXeX0rck_7kmiCpKL1q7S86-uzIagSzH6-PJKXAeqIM5eSjMqa6B4ZqNo_32DnVlqk9jg2ysf6ZYJ5BwjKnSP8n6dLIgisjnuuOD1XhWwu6G21ttzel6zfzZDHwTGf6Q3-eyDDiXsWE2Q=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEG8GyUwBgXLKyX3CRB7nrVetLwRbUPQySNPNbxPTmfPSn33izP3_MbcgmEL1PmQ8Rm4H1Y3jhFnNh_5S__Dyj8NvH6ZqGtjscEz3eiGCkuc-SXoPEyY5f6-t-PoSP0HZi4PIgOJJ9pr_qzyTpz5vD11IgyrEE0I8kAezweqoyXPJTTGufFRAylGvJCjyg=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGC4H2doDK4Wt_HqkJGuxdZDYIm6mbpimrnbXpoHR-vyt7gz5T--UP4KPivPVjhfQUA2eddI8KolqWEEn7mKzj4QQCk3kiyX6bDN9EyGV0XqftiSY_HPNLGOHjEcxauMSJjwqqnhjMS",
        "https://www.linkedin.com/in/francesco-ferro-a6a8497/"
      ],
      "search_queries_used": [
        "PAL Robotics Japan office",
        "PAL Robotics Tokyo subsidiary",
        "PAL Robotics Asia Pacific",
        "PAL Robotics Singapore office",
        "PAL Robotics employee count",
        "PAL Robotics LinkedIn",
        "PAL Robotics news Japan 2025 delegation",
        "PAL Robotics Japan activity",
        "PAL Robotics careers Japan",
        "PAL Robotics Asia hiring",
        "PAL Robotics leadership team",
        "PAL Robotics scandal",
        "PAL Robotics downsizing Tokyo",
        "Francesco Ferro PAL Robotics LinkedIn",
        "Carlos Vidal PAL Robotics LinkedIn",
        "PAL Robotics major scandal",
        "PAL Robotics downsizing"
      ],
      "verification_gaps": [
        "Confirmation of a specific APAC regional headquarters or entity (beyond event participation and stated intent).",
        "Exact employee count, as numbers varied across different sources (an estimate of 150 was used).",
        "Specific commercial/business development job postings in Japan/APAC from PAL Robotics directly, as current openings are primarily Barcelona-based."
      ]
    },
    {
      "company_name": "Inrobics Social Robotics, S.L.",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "C",
      "asia_tier_evidence": "While no registered Japan entity or APAC regional hub for Inrobics Social Robotics, S.L. was found, the company is actively exploring entry into the Japanese market. They explicitly state an interest in Japanese companies serving as strategic distributors or sales partners for their platforms in Japan and the broader Asian market.",
      "industry_primary": "Digital Health, Social Robotics, AI/ICT",
      "industry_weight": "High",
      "company_size": "Small",
      "employee_count_estimate": 15,
      "why_it_fits": "Inrobics Social Robotics, a Spanish innovator in digital health and social robotics, is actively exploring market entry into Japan. This presents a unique opportunity for Wendy, whose native Spanish proficiency allows her to bridge communication and cultural gaps with the Spanish headquarters. Her business-proficient Japanese (JLPT N2) is crucial for navigating the local market, where Inrobics is seeking strategic distribution and sales partners. Wendy's B2B commercial experience across marketing, sales, and partnerships in multinational environments, combined with her data-driven approach and cross-functional coordination skills, aligns perfectly with the needs of a small, growing company in an exploratory market-entry phase. Her ability to drive strategy and execution at a channel and customer level would be invaluable for establishing initial operations and fostering key alliances in Japan.",
      "confidence": "Medium",
      "confidence_reason": "High confidence in HQ country, company size, and primary industry. Medium confidence in Asia Tier as evidence points to active exploration and seeking partnerships, fitting Tier C, but no explicit press release on a 2025 technological delegation *by Inrobics itself* was found, though the intent to partner in Japan is clearly stated.",
      "role_archetypes_likely": [
        "Business Development Manager APAC or Japan",
        "Partnership Manager / Alliance Manager APAC",
        "Marketing Manager Japan / APAC"
      ],
      "flags": [],
      "suggested_next_action": "Message Jos\u00e9 Carlos Pulido, CEO of Inrobics. (LinkedIn URL not found in search results)",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFFW75IfA-jgD084lBsSg8E_q8lF0l0X8L30G0Mrv2iPJ8oaOc4VoiYq9RA1aQfk7IogUlL6xkp7maIhNs8OS-smAy2Y216YM7opuaHPyjpUcigx91OrpMdvQ7utZj8r9ur39pOiNo3rYBi61wVd1egwBkaig==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHNsB-aspTPTSKQT4nTrx0AAsG_mLO2Yreyd1bhwUCTcy4fqw1qsnNXzi9vqPDe3B3X5GFPuLpkXzuz7kB6pGNFT93Ju0b9Dl_qbMcC0OdtN-ZGcpIVnuuAQeOkBZKSRXceJhw=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE4H0eKDa-7guBbeVdw5VdU_tT_azGykKk12ZUf9TCLOkZyi5Jx8hotVjUpZ9XiFSEzptkFGdzjHukCeavCirHHKlqG3kV6xF6Q2akaNmsuFLX9f0WjmatH3PFFQ9A1NH4gupe_9_fMNWf4",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFq_V4agfjWyOVuikoE_MuHJnVt4dPqBq1-AVGCL34fItSZksnq9OtBARn0d8QN1lFc3FjzNRueg6nMH0I_xdj_reyCPOK8Ko3DfnLus3jy6vzjCItK7rOFu8mhNzfwQILqQ4KKGitXY6G7jRWq9OF_XVhl2V-j",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHGYlQM5Tag7OBxeB2wFtqhePz0UYS-M38-L9qK5t2dfnHOQlDUJBUlH1ivu_rSXswOdh92eLYn8BhQTpMfB1u6mh-VCE2fl2Q-Haa1EXFY7fzsE4lUUjYKj9jqtO2ym6oh_0TYdg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGu6D6wcbqIx6nimSrZWZAyNrr4xjN3Dc4vgiNiuUuKIz3Z9hwjT2FGTbPSNaXkIrXL6QVF2_jCiR1-ReSgQdpiY-ya-nSpIMqVdP_D-D_29f4FE6Do0i5sxmM=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG6fCciVR-GKfr7TKzdXA8qzga0oEzEWHWNiI074pChcSOY1ES9ZLTH-FCPJh8dN3npAJo512SzQh00UMhRZuWpMeqIpgu1CM4Uu4w4QwKUDu-BCcrzjbz9R_HVN2JtI0tu0PAxuDc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGtp4FSIglOUjCaVLnDRwMCoHgikorlFNZQC-DAN0qDoE6gV1BfJWLkjtxv_s4MMReWntBQohG_ilVLWI3ZuapZc4kXxsdHjBU4KTbQv2fcwbg6_qHL-iieB3fxtI2L-hWI1xrIDGKI6BUtwk4El67pOc2ajsayV4fsszapt8UDC8Tj070dBVLHhLqHNhFfkg-NYu49kcZtCOV_dYjWvnN-KFaQw_Re38KaeNAfM902P_0CBy2mZOvQ_A_04nswIdUX-DhW_X9dcr2h-hSEEQ=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQERMGeV7qHvYucGmfdKkPgGXn5ZRA7P-m90YXCSWFsIDJlvj8aE7pd-ZLflyNohmvynDQxCawMref7mjskcHYyidKX2-PwgOjMDoVnRd8CvJ7oERgoBN43U37n8JQ=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGeFEKsG1OtR4feBQie07yuEwKm8vr6yRqFuCMF_ZEmRUUbFG3lV23GkwlQ7Gq15clcIva6tkvmAAouWuXsTXpPxs5mpHAD76x_pTrRRUf5jm-UkjQG4Y6Ht7paNa5JBpTbhsNFY7vjY9BlhStMriQVbuNn4I0pn_HwluE2iteuyzI_",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHDu5rmMQYZVkpZ8vh8cKDY5Redm6_RLMW6kXzxDIHbV7C9SJr0e7yvbf5todBqujVDEsW__8aKFnIhgH2Wv3BHTfUZZID2OegGGvB75UU477nBveCuht6710zUWFUlOsAZVRMlohgEE70U7x05hjLl-NfgaekMZVkQxlkEkWRtot6XkkvJZMgrVohp65am43mBq7dlBuZ2xXuoKgMhsloTuCMX4e9EXrniPLCYGA62pDA="
      ],
      "search_queries_used": [
        "Inrobics Social Robotics Japan office",
        "Inrobics Social Robotics Tokyo subsidiary",
        "Inrobics Social Robotics Asia Pacific",
        "Inrobics Social Robotics Singapore office",
        "Inrobics Social Robotics employees",
        "Inrobics Social Robotics LinkedIn",
        "Inrobics Social Robotics news Japan 2025",
        "Inrobics Social Robotics Japan delegation",
        "Inrobics Social Robotics founders LinkedIn",
        "Inrobics Social Robotics CEO LinkedIn",
        "Inrobics Social Robotics scandal",
        "Inrobics Social Robotics downsizing",
        "Jos\u00e9 Carlos Pulido Inrobics LinkedIn",
        "Tania Tejada Inrobics LinkedIn",
        "Jos\u00e9 Carlos Pulido Inrobics LinkedIn profile"
      ],
      "verification_gaps": [
        "Direct LinkedIn URL for Jos\u00e9 Carlos Pulido."
      ]
    },
    {
      "company_name": "Robotnik Automation, S.L.",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "C",
      "asia_tier_evidence": "Robotnik Automation operates worldwide with local distributors, including in Japan, since at least 2013 through Nihon Binary. The company is also actively exploring the Japanese market, as evidenced by its participation in a Spanish Technological Delegation to Japan in 2025.",
      "industry_primary": "Robotics, Autonomous Mobile Robots (AMRs), Industrial Automation, Mobile Manipulators, B2B Technology Services",
      "industry_weight": "High",
      "company_size": "Small",
      "employee_count_estimate": 66,
      "why_it_fits": "Robotnik Automation is a Spanish company, aligning with Wendy's HQ geography criteria. The company specializes in autonomous mobile robots and manipulators for B2B applications, fitting Wendy's background in ICT and B2B contexts. Robotnik has a long-standing commercial presence in Japan via a distributor (Nihon Binary since 2013) and is actively seeking to expand its engagement in the Japanese market, demonstrated by its participation in a Spanish Technological Delegation to Japan in 2025. Wendy's cross-functional commercial and data-driven experience, coupled with her business-level Japanese proficiency (JLPT N2), positions her well to bridge the company's Spanish HQ with its Japanese market expansion efforts, potentially in business development, partnerships, or commercial management roles. Her experience in logistics and supply chain aligns directly with key applications for Robotnik's products.",
      "confidence": "Medium",
      "confidence_reason": "I have strong evidence for HQ, industry, company size range, and recent Japan market exploration. The 'Asia Tier' classification is Medium due to the reliance on distributor presence and market exploration rather than a confirmed direct entity or staffed regional hub.",
      "role_archetypes_likely": [
        "Business Development Manager Japan",
        "Sales Manager Japan (B2B contexts)",
        "Partnership Manager / Alliance Manager APAC",
        "Commercial Manager / Country Manager Japan"
      ],
      "flags": [
        "Country Manager / Japan-public-facing roles may implicitly require near-native Japanese, which could be a soft disqualifier (Wendy is JLPT N2 Business Communication)."
      ],
      "suggested_next_action": "Search for Roberto Guzm\u00e1n, CEO of Robotnik Automation, on LinkedIn and investigate his profile for connections or direct contact information for international market expansion initiatives.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGAgwLJf9tpWc0ZF9cycQZMMPaFScV5vO5_Eozj5RpWLyfeRNiuRtXlNnfkRD9sWhE0aeNCcDV08oNaUuaSP8qXolRdil-qA0L3qnsv-WgaqJVgFe_o9jcAlzeO8kHHR_fCmXc9NtQMdVICcqhgcswV96hFmBNBVTE6_QnTeHHlDguS",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG1dbqoLx5upB3Jjxv5GiiJ_F_UxqP8d9VyBF6KVU1DVHoRi7ODYtgEDG15LUlneX-D8y89D1IO0M3JUstuX8xGlZ15EbGN0JYT1ZreKFi5PuVQ5otcZWppMgl6BGtg7mSWABU=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGhnVNOkpWRY3PKT3Y8Eh55CkyVZ-gmqlKbeNB3J9EmCWqo6F0XY1T5MsZBy8kKDu3XUYvmvk1b0e1iWS3fH7em_56fiEra_awqPpB9O_aemt_ykWdOZM-jC2sPS0CHRyCYltMOupR4xfYm-KJEaLXnJCC39mMtsrY1C8HDZt9vJvyDWl7JYDOswVll6loJVyY=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHQPlxBn9aYnZnQ9epVI-rvgxJ2ou9pH_nmEdOUN27SYTp6sQoSUnY0qj_pSxuO3rE31SzVEXoL7CvQ5uCHo2BhpDgsb2ZmPi-xAsnmtFa8qxuqcvOla8m36eLyCfTtTwhCS7HMPVjjyaDCGQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE69IMd1Pk3E4OVqFKD4WEOY_IvE0ahC_xRxPFT4TQYvQlStFdbLuf3cBsXQRTb1Vz9AQ1_Ma0EAdO00WxV6BnAmuTXriT54MPzqjnZPdxQatyqcf4omJARjVJRcPIxo0xFsIeBaIvpseEAApj8yJf-BtFsMLA=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGAMMmNeRYckOCsh30Y75Er3OgRGYp4yiEAdul_IaW9EeejPz8n7WBDul-1hvsx8IeGwztXEgjLU-SQIKGbB1izFZsY2lW5_Lk-RNCqx1UbFUr2bRiFNbgRQRh-6vn6sBupd1676JLImZHm",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGQHvKZ_j7zSy-UbYhtUOZ71tBx46pUNki0uIR-wlVHEuhp8BTmJ8Ix6RcfI-MxeLM7jxYmKWlbvEzDCV6xjd-vUJoqXARdiDwb5_57UVJ0T7cz-9hqCfbhtSR5SXB84BU76RBW8w-HERNJ8I4W9crHd-tzpfI=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFeXK_drg84Y77ZEwFGsgSwb82BHRXqYcrvB97CKgch1jRjKlXiWqyOnAAwZmgLrn8TFFhWrlbh4iZX_V1ackIGWoEi4g42_Hs5jnVTMnYOHmsRerKwZvtNH9H-Lxtu-G8UKASwJ7P",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFtcL7vbOEM-C_2mYiNXGTNky2-801hEo9l9SNe_amnau0NmLL9FP1Ar104v-LYVIlDQMAhUyk4Vxc7x273YfIJVEaHMTCGrIDl6vfrFFa8dUIkeqrNQE6TJj6wG-2o69AhAj_9AgfAnG_1DQIqVw0tEhg1lkMkdbPgKFhbgFUe8vvLndc42rqeXf1w6k7XPDFS6JQBXVt_GK8=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF1qgTNIU1c4aAmBPUJPR5K4Vl4tfR0Uv4S0bxR5Vtq_CjlcgP9TwEFl_TA1Jag3oF-RGisX-78HBYrTc8BFNulsiPo9N2NHPobqFGssjCcIM-YO1qVoeXVtecmqCsdnrRaUxqD8J0Bkk7QjeI=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGn435uaDyAM45gIOwK4tLfrzIMLYhx1DVz9im9WVPRTxs7X-kYmFen8kgypiiljbOheGzzSJBHOm3Msz7_UmOk6dwZjJRGjYTjze1J3voc7qWzcYlOaT5Oq9pX2oKaY5pbyRrP9MfIenJEm3sLk6Tx4Ts=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFd1N3SSqUojxz-5wHFIWPnus3YPWWUGH284yci3x8S3PfVpEe1Rzv4GOBIcYXviSVnvEvQYIaSv-O-7KHJLFtVtpY4G6A06rWXoY4sgzJbE",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGLi9qgHX4VXrqHefuVh96_f75LK0ma6evmfXxBk1w3aLEjuophenbtH8vQNXwo2Lpl0mvhwTbjkyeZp4btLzzSUFOdM8m2fUmHmI60hJTg8LEnZkhrRiwIfP31jW9-PZxNakXw",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEeeoD5da8gzatNU0s57zxWop9YF0jalzCeyp9GP2EZr9HO453cu5Ap8n_m963HEbQp11-CK7YJi5IFjxCkm5RvW9s4YAuOmaowuiI42oE-4d3dQXcjDkY=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFxGfLZAIjeSvPHzvWiv0zuVsAZdrzDs-0nefc6CqkX1a5hKKHDl6c_0B0Ao60_1QZs1sEFNHYCTTJKG9z0CgqqNpCEu4IhDBjvsAJaquYP4iaHuJxdtSU=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFj0UvC4LISviCdFbe7Pvr4q5kutjOakqA6mK8uD7D4X-HEnW2AXcyJdI5V3EvUUkeU7gAPrxGGjligCr7wV2GEaYP3Jg8O0_omQZiFCzpLlzTQAmIMXZAQ-mTm4pNHiqf2u1db_7Rgc0S_XPQhQlL-tZ-XBbylVMSP-aZ0zfgoQtjATfIxYR6m9AyluNA=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG5KH2-ZQdzpvewvYjQATY6pq20qgfQehFtKwCFH9cvc7fihREBPLTA4XPpoy2M0pNM5Mx7rHs-101cBi_FclQiS6768xPZUsfRO7Fe7T2nTnmma8-9M29EXnpR",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE817ft1qezlyxo3KPO4J5yNlDwDt5Seev7yxEC0NQTNjBOrU150lWEvf_qri5a3cAhI7ctjYjZgKR8OBuygBPz-ZHGmYOXowHVdrdZtZto6_YxRd9RDEtJElLr08qr7WZn2QZ9mTeBAUfJng==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEeM6u2wMy8hzrRkIJ4TGi93bRhAmpPqkSPOtFrSzI6BHdlavQkfZxYd196MPmBE-3MAt2IuFb8MCvEnl2nZMlb1AyWslz1OG5txnAQYJrJPyMFy7RwGk9W0M64kMMGbwLNAV6zlMZWBZwSJtd-wmDz8e43qob1wc5GpCw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGYM91s13U_t1zA6TydcOzqu4eoiE3z8rsSV1ptayHO6-gYbrZ8TpyZv0ZjpCmVyeubiUDSl5r76GLl7tlHINEdoSCYqwH7y8MIU7yRsbgTvf-kVvoPYQbaCjVMksSm104NNCSdlEBqepeGivekGwlsPlInpa4O-6PBSN_1X2jPi7shc7LizI48AqPeO8UcjmohWNBHXK_Pt4b7BDpW",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHhgTlfC9O9yYUhDwFE9TmFyZ2bf4u11yA379yl34HAx7FBOy2fatF9tEACVZITTWQ1E1FXwbWzP9qH6R4gGQvuvs13tu19XkNUIT8yP5DoD0WvbqVDYkMkl6RYRWngwF9j-AKcQEakQDvGZilEmyGbpFycp1yg2inA7Kz2mGmrfNhs6LXfe_AXl2dn",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFISWi-jYDV68LLv7ARAZkNOUDQ9G6xuscO8v9Rzs5V81qfAQ5Stuvay5d_yjWsqTodBR1UtFC3-C0Ry19_JisMEOkPSkZE_bGYqgqExMwrzP4Ru9--RF8QilPlrw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF-BxWkOHap6s277l0xWxlMiDGJVi0ECkZF421cxmyNPwX8tGe9j4EjiezFFVnRXP-DJjw9pT6fT3bcvUOghgiTMYsppPLWwzf8S_F8goGFsgAT-3nk2mF2cdwjIwQDngwJ7jxQ5vs=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEMXnIjAk2A9eAQo7RNzZrShuc91ViVHnA93pez--id9qEdPHAN8H0yAS2zmUjeUNM5DKviMuuqbz8YEVJbHe1n5oWr0lHA_wsQgpnl_FjmI68b9tC5HraV50TQUF3jH7MrLfIq_pxi0Y8ZwnpSgkTMCsr57AoDROIV4aDQJ92u2to=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGGjKawaW0LK6BZdbuTAkhhH3bp50jUSqEEF137aHWKrkj-TIuDyf7bB0QbCanHsAmNfQeEKDdAgsrVv0TRq22_-i5Nfvrbj-jqj4zfUZ34mHIgOb4u2CBiUkAgtCDS6FJiHPKEMIMxYYhkPiy3jFw54LJ2EwDw7IPlaaqj70UZj0qu0kTZFEOzk3og",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGHLIoho0eI9a04sgjY8rao1M-koQ4i-YvA-sEbRTPiyqbpQz2u-bPPET9A2Ag9mWgT1aHrAkJj-cjnALxfgu8eifjYyTgJ4saf3N7H5yCVR35YnUtF8TL5rGT1Zfuooga39f-eQQJcwNesbVF_GnCXUqB3etq6l0Vp5j7BY5wRsw4ivKu3AzIZ8IhuKfMUWaBcim24BkZ5Wbuf0ogKAsvZftoZiCg4Vasb5GeEnElkoyH7_cJS9KLSPimf3dxw",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG8zafFkU_eCmsSdZTSdgbFtisngKrFguahYbUiR1RRNHLLiMNWEC1eT-5BWkOA_tuB6Xe1MpBtNwDa9_odk5fzZ5jzPtlT9cjSV9-7OpuAyqy7P6yXG8DYsN2V0Yl5G36R-pFIP1BofiE-I43bvoRmIu1HqbU8xaQGJG-w5APRSPNmzAvjZ6cjfup5YShyC4azhEzzV5RmggmPoTYJG1iSg4UsuGc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHt-7WMmuVa1SleibMtVQmgD-Xl-wD4Y93YwhSzUAubiZx0A1t3seqB5spU6qTQ6clyKxt2lYheYFwLBzHKrxqrADav8JcHn_lUIyPANJlNq1NelAWS9C_ZdyDNe85Jy6hZBRIH1Wv6JZ9k6hvfxA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHAnYPUs48OOsbnECIugGUsIJJktmLyaLHw2qcC7HqCivdROuyxNXCsgNKZW3CiiAbV-GqLlFk7IH0SQxh9tcsHjMCb-M9WF-XiFUSbRYnYbAJMT5QLSRbxyUz9kvl-cCgoR3Klc1fvkHNh",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH4M9lSkmUwX1uAHBzeTMoV55Qb5MPvunizocB64B6ofTqbXgAoWGNgDBnRbOXUCtgjYTLtnDmegeLe8ucboXpFulTmnoUbtHYXDsMbRUYFlwdiFx2RxLtiIfheZkoY4wyj"
      ],
      "search_queries_used": [
        "Robotnik Automation Japan office",
        "Robotnik Automation Tokyo subsidiary",
        "Robotnik Automation APAC",
        "Robotnik Automation Asia Pacific strategy",
        "Robotnik Automation employee count",
        "Robotnik Automation LinkedIn",
        "Robotnik Automation Japan market exploration",
        "Robotnik Automation Spanish Technological Delegation Japan 2025",
        "Robotnik Automation news Japan",
        "Robotnik Automation Country Manager Japan LinkedIn",
        "Roberto Guzm\u00e1n Robotnik Automation LinkedIn"
      ],
      "verification_gaps": [
        "A direct LinkedIn URL for Roberto Guzm\u00e1n was not found within the immediate search results, requiring a manual search on LinkedIn."
      ]
    },
    {
      "company_name": "Viscofan",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "A",
      "asia_tier_evidence": "Viscofan has a registered Japan entity, Viscofan Japan\u5408\u540c\u4f1a\u793e, established in 2021 and located in Tokyo's Ginza district. This entity, which had 2 employees as of April 2025, was actively recruiting for a sales position in February 2026, confirming local staff and commercial operations.",
      "industry_primary": "Food Casings (for meat products, including plant-based alternatives)",
      "industry_weight": "High",
      "company_size": "Large",
      "employee_count_estimate": 5900,
      "why_it_fits": "Viscofan, a Spanish global leader in artificial casings for meat and food products, presents a strong fit for Wendy due to its HQ country being in scope and its primary industry aligning with Wendy's 'High weight' experience in food/agribusiness/protein. The company has a direct, registered presence in Tokyo, Viscofan Japan\u5408\u540c\u4f1a\u793e, indicating a commitment to the Japanese market. Recent financial reports highlight positive growth in the Asia-Pacific region, with a 6.9% increase in Q1 2025 and 2.7% in H1 2025, suggesting strategic importance and potential for expansion. Wendy's extensive commercial and data-driven background across multinational environments, coupled with her business-proficient Japanese (JLPT N2), positions her well to contribute to Viscofan's growth and customer relationship management within the Japanese food industry, especially as the company explores diversified solutions like plant-based alternatives. Her B2B experience and cross-functional coordination skills are highly relevant for a company focused on market penetration and operational efficiency.",
      "confidence": "Medium",
      "confidence_reason": "While the company's HQ, industry, size, and presence in Japan are well-verified, a recent sales role posting explicitly required 'native-level Japanese skills' which is a soft disqualifier for Wendy's N2 proficiency. Additionally, a clear, currently active APAC regional headquarters entity (beyond country-specific offices) was not definitively identified, as the Singapore entity was 'struck off'.",
      "role_archetypes_likely": [
        "Business Development Manager Japan",
        "Sales Manager Japan (B2B contexts)",
        "Key Account Manager Japan / Asia",
        "Marketing Manager Japan / APAC"
      ],
      "flags": [
        "Roles requiring native-level Japanese, such as the sales position recently advertised for Viscofan Japan\u5408\u540c\u4f1a\u793e, would be a soft disqualifier due to Wendy's JLPT N2 proficiency.",
        "Viscofan's US manufacturing operations have faced environmental allegations and OSHA citations, which, while not directly impacting Japan, are recent and could be a reputational consideration."
      ],
      "suggested_next_action": "Search LinkedIn for individuals in 'Commercial Manager', 'Business Development Manager', or 'Sales Manager' roles at 'Viscofan Japan' or within 'Viscofan Asia Pacific' to identify key contacts. Send a tailored connection request highlighting Wendy's relevant B2B commercial experience in the food/protein sector and her business-proficient Japanese language skills (N2).",
      "sources": [
        "https://www.google.com/search?q=time+in+Japan",
        "https://www.google.com/search?q=time+in+Singapore",
        "https://www.google.com/search?q=time+in+Tokyo,+JP",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGOiRPlzR9WgRedtlwRyO-w3MRwoKOJOr_0G_WNB4KRieUhhxK_TtIvfCBsFOk_BbRaBAsaZUBq6kioWjZSBWkLpW4FfGCR37rs2qXzsoCEKISR9c0FvY8qLU7d1iljB1JzcVHwo7ECZdvv",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHGOcKoxRKedH50HE3R6ib6mFXCvr9uuvTO0PbkKfsvpwhgRcuIeKzl2Yfn4vmdnlrRkceHtYfCfEJCf9SaEEx0bBXGGC-tj0nEfK2G6yS6ydiF-n-yUvvizAVrYuNhzZerzMcBxwGVXmw31ylL",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFVdLwaE2Y_WGkSc2qqWwq6IXGyLl0DkiYNxu0QlLbEFvfgyPSw50zeoTPt-GFhx1J3oweWwDrKAZ7WxQZA5GEcM6Q10D3LLW5seW1EOA_tPMNKW4gWLb-VGvxLgRBvHQOp",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEhiscNrwbS--Rs07PLfSmGU9XS5axJ6IIRBHMOm_QXPK2ZFZIfH2CFCdpv3-N7erBIegENahuWhCOrIT4sjG6cnwULKmE-oKayp7hPo9FHpnFDy5cRcIOZLOk=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHBisiF4aKQAnHeNRI9E5v3LwA_HlocbfQRsieI3rCg6ohu15jdD5Ko2KJD-rlsgu6AJBXcwEtfvqoI1v-9J8wrxXwU5ZrAj7tsaMI2eymVP1aeAzCikuyiE83vZiyTbcgDpmWM_uKdVO8AQML0t-L6VHmt6BNW1z3KUqOxoHeiOvGlo2kG72UuuTGDgdFYquzYoWIRso7cv8qHA9fVMBFVcw3KW2AaJawMqlYHb3gm1XtnqJ-vJ4Y0DempuQ8x",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEDvBllwmbNx-x-eBnUIBuJsYlBnGN7RLdRJqhfp2egiM4yrtv9XtPObnWp9pmHmzcxHP4Y-k5-ZaORHF9lJa2h8sSwKYKE6J8_DKAqi_rSZ_SN2TOvAM9MShoYJTi8SjbyDGX0o0rdXdm77yyueFhAMqQqy0Dg73cnYXVJCK1ke_dASc7twDi5NQc16TCn8DW_cH7VQB-_z63qpL2U8WC4msDulV5E",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF9IbI-jbFR0WyADjxOXUbWdr4ojl67NLu70Bi5QR12xOvdzjTY2zIj58CbyHfry2OoUdNvFyKw8d_vo3UmqSqjTrZRRQvkg0hf64VdG_p8QDL_UUq2bzVuZKR-9sZBEoHMRcZnOeOGJo-g4JgS3B9yrw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHp7LZG18iZDoBHV5lMloNnzjGAhag6h4pONi7o8Uewx5Ve07826mSpykRxK8rjWE17E086_eRPWqe2eNArR-BOwclfiAv0IHteFWMfdujy6jmbBSgVgXrrUBYV8Zu1juc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEDl9Y1kCMXC1K-kQtVBHvfwvkEnyr8hy1K0n4sMU_gPWcX4mxFdRZ1EYOt3SOkcmZBwcGC64GK9-dZVCaGeatvlwejp4oM1iqEaVHTNnHMblm95Jd2P84OM3a0q5w2oeUIIoZFokU=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHDNUbqi24Ld4qyW1G_QaHgD3CYbANetmZbywvI34Pkd5tHL-tzPYa-fGZb5ZXS_SQLGR544xKs4T-aSPHUn_mgIDa5v4SHzhx0bx2vz_fccFSjNvY81tlAMNvXcW3Rp7MpJmGDdKx6H0H61gUIA8B0hmyH8OR9OiSB1",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE5Ps838QTxVeJfd0e6XKWOjfY0NvXSA0vSTIdEaw7JbY6ngSNZKV081uRU7tSS55XFqlK1PjyQHnUYAL5BAAH3DVhDuPyKX6TtRDRZDTkDIpBeZ57Aes4XymzPFA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHKUPWbOaBC9u5MMtmw5L_dFJSQLIB_WkAtyrZ9FU0nDgL67jCY1cNOogH0RTjFoTu6-MVs8tM5bW-t8e3PvpcBYGI_el8DiR7-hdsMx57PiZGR5D639_f7fnumPplia07Mr_s1xGDbzKvxMnGRAF5ZXz3s85-fe8DE9g==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFkRUmCVAFwdT8yErQa_Wm0FlXQ9iaOPXHHvr2UvaiCKs7ZjSO-wvNo6YGEL22h3dYaiCN-tVisCIVunkGzXhBdKWEx4Txjjn9AqZsfqkfV1Spxv-luf3g_-PL-euAxrXssrLgECtaPOIODDBDSWy5nA7RgpXt5BCLehHDw",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHDdPSykLbaOvO5uAsrMMncivTPXEYT-B_Qap74hGBSfTTETOR7SOIzOR5XoD7Q3CSBwsy71c3C7YCllZZ5hWN3LoT9P4TgfHilb-lhCHieJJsT_lbnsp96_i4rtyVL077YOKjSCd4mQd94UCR6s0HAaopVmQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH-I4iChuMhVebiAawTvQggnbHEr-YlaW3jVEo15H3kCZZHSbCGKQUTzS_UFkVwvr-j8v_DJYQ1gmztPPnozyzk5n409zviNEm4n_Xw6biqgqVlP7b2UKzrUcJndqmzTryk2v-Ne1-A3WW3StNL4qE5qCbaAibnkxECUS2E8u7I9t_JULhD6kT1Dc9_rvqM_sJ8pYUSxh-T3kTyIQyurqnCVjsmZJCyd-CONbBFX_Gize4d1KRAVI3ehQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG0C_rMQwTOPQcWvvRl2qAXcfG3hLM_cEhWIXwsOP6v_2i5iTtdCtJJjJNhTVEdi5xhUI9hzbeHcm3LxlzU5qXQLO4Dl7iYRy90rhvnxwjCC5LBirMdKTtyc5Avfavrc_XGc7E2GrrdEBdnaR0sV6TosTEQKUbuAM8=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGjQF4p7h31Pwq64iV98hueIZPqM7LF_4GHLnA-V-e-rZhlhE2w4g95_nRmOLwXFmVYv-D0VjRuyM3PI0UXBaWZ61LSPidIbQiEdTmJtzl-UAKD_3G8UyN1GMQnsfaIJ9pc",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFZHWFASIKpNFBdD8eCbN8c-37XeYzkcXRXkq8Y8T2AHt_YFjM1L2GJ3YCVNIvUgYxfprjAyebD-YHiG9KZkvMzVBEd9sob65PMcRA4dXUAObSdLRLpsGdfiQ3KkODQ8Kaq1VPAkKBRCw1N24-qf-mPfZ6ihtp45uX_MVLC2VIjSzFCx9I5qC1mnjwOR58=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEIrlV95K8vqeFUsBluoTmQQm2hI7PWysa03V251bLuoFvcsaxt8GE3Tq6BxOTdBxHrRsCcDJZTN2bzUjADBWB2nY1DyHzY5rxaUmc-uxA2uIYqq49PeuaBsUR127WdKyc05qL9jgeUrdScz8z6yaw=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEKS3nC_wdF1eoe94udwUa6zkC-qHqCmWMxl3MN2rhJiSfiexi19iGESY1RYoK4bpfUHCRmm-NYRT26N113DA04KcN_6GZtVOSuCxAEQiz54Q67wMSXtav2",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH3pIyurZfVCorABe4bXnfiW62WeyBGWfAi7Cxo23dYGmM6p4C1oR9gjM8Cxm4ZJkzxeYZemLSHcmpO34bAYJKDs0loCl1Pqujw4BZ334C4vQsyLT5ixwwSDs2Js1LV_rAgOlmL2Csw1jobgkdbIsoYr_sqgvRnSBYXcwFZenzk3OEYClisi3blKDEBToLP3CiWCiv_yAhPbvJljBzPS_3et9WFV-Npoaa8EGit3PMKtxovYMog3QMbTQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGa6L1JiaMds3g2KhwOxHW3u23jYR-jWjsHcg1rvEIXKOThvHUFA4PbAo6jNLt9AUx4jUiEMDXubvVQ08eDpsde08mYewI0ZyouecX8I9W6FNJCUSpVG0lhZyv8Q0a9BSJZaDGGgUOPLtkPHY2VrZM6QuKMzuUlsKz4DvOd7YE=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHeTczIuFrfGC9Pww4vevRp3rOh0OE9QaGdsdoOYHu7Bv3CwOMgix3rP5ZK_HhwGvGo7ZLCqkFSh02awggosI4hmq-I7w0cvZlkfF4Vu4_lJs5ld4lyaJxBw9fafMcgNIhP7vVybE8SH_EbOfk=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHa8YBMDlnOzzbsTTtMXTBeD8RmMEhFoxgVfIpD_2d81D1cCI65ZqfnvFZozYWAVUyC_EscWxJ1krQUVkjYOdwgSCHgSey0BmniEdZYetWS9ZbtVjk9eeKIvw0gib0uysT93R-J",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG55UMN0zLSssrkvlzYEnnHLI7DjdGSONaSV2B6MTWPjw-1GfbSpH-AKYLDWpgLe5OPjvdq-fjxp6eZ26w7948I0qQEoJORM_Iykw9M84--3a_r5_CNnbRICtM8tn7tIBbc1CK7UO1nLIP_NZohHaIYD8w4KwUXuGXU",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFLyDrTGwXjMOtZKSg4S2mK5Pfl2h02mt8MDP2CRbmSC3wj65AemtviJFg0Kofhv4RpUQId7AQSdwL4sZ-Yu-KCqlrTfloQ2bdyQJKXY5awUxFGu190sjdDCAsre6r57cW11c8-YGTGdUoB1jU=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQELtM2uZ8R0NmcZAeFIzV1JNijb3Vjts4wiiEjeDyb-NK5A9JH_RM9G6CaZXsFetv2k3cljXTG1u0MIVlqroaP1c8NpaBxiHVOBDLH-DdaL5USqmanc1ufyNs2F9tewnYmUTFkMzfAmlkuRaJVjFrEXGiiLeRD1TOA9",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHRhuQBaE7SehuvN9lP0c8iF8u3u6U-Fb7TQ9PSO_wovAWFBsN44pWkpro4D7ZDaoVkVWv7LGJE0lWOrfAbm2GMPn6gNGID01mw3zhhyH2EjWFoeuT2uH4wngKoJazO5ZXm2o5pk00RBCwp1kcBOg9TFA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEBlVCIJYmFufi27b4bx9Z4JC9ipqzw9LZSQp2gl2ZmHP9pw5Y__5hGwDjKQxxyaUxchxf-Ohhpk_jy4gACQLDsG2rXPO3xQ7LjlgWhmvdOUm0nduuGgH0oL2E2bqe9vhGzO96OI2AeEACw8-Dhkjz1",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEMwc9F8aCBXPieXv6v0i-W6iQzrEqvEIihO39X--3t9zsFaHTCv_X9QLIhJEyIf2UnVb14hFH08eEYa3RMpOOPMsQjP72F7-tGvfk5RtKDpk4VBNgd3-bLg_x9jNbZxzel2MX9UhQyKO_gyWsId1zNfewjL_i44x-RQILfPmElUpVWNDPnP-BMxL7iFf0eIbcEly3-q32I5hFTzgFGDL7SDNUYacXeYZ3hpA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHMyI1-vB8KQ-kjUesStG4vXSGShTdyOS5CmILW1pjK3t7TZJnOIbqnSuErrUVLruXKmCnTSrRHfjMGAlwRw_OZh-XVWSbrRUIE4_l58nv6nPtdvZG3fZWoO-hIjtU4rB3epNJMCeBi4R6-LTmC1ab-"
      ],
      "search_queries_used": [
        "Viscofan Japan office",
        "Viscofan Tokyo subsidiary",
        "\u30d3\u30b9\u30b3\u30d5\u30a1\u30f3 \u65e5\u672c \u30aa\u30d5\u30a3\u30b9",
        "Viscofan Asia Pacific",
        "Viscofan Singapore office",
        "Viscofan employee count",
        "Viscofan LinkedIn company page",
        "Viscofan Japan news 2025 2026",
        "Viscofan Asia news 2025 2026",
        "Viscofan Japan trade show",
        "Viscofan Japan Country Manager LinkedIn",
        "Viscofan Asia Pacific Hiring Manager LinkedIn",
        "Viscofan scandal",
        "Viscofan downsizing Tokyo",
        "Viscofan Japan\u5408\u540c\u4f1a\u793e",
        "Viscofan Asia Pacific regional headquarters"
      ],
      "verification_gaps": [
        "The specific LinkedIn profile and direct URL for 'J. S., APAC Deputy CEO' could not be found directly within the search results.",
        "The exact number of local staff and the full organizational structure of Viscofan Japan\u5408\u540c\u4f1a\u793e beyond the stated 2 employees (as of April 2025) could not be definitively ascertained from the public information.",
        "While the Singapore-based 'VISCOFAN ASIA PACIFIC (PTE) LTD' was identified, its 'struck off' status means a clearly active APAC regional hub entity (distinct from country-specific sales/manufacturing offices) was not confirmed."
      ]
    },
    {
      "company_name": "JBS Foods",
      "hq_country": "Brazil",
      "in_scope": false,
      "out_of_scope_reason": "Hard disqualifier: JBS Foods is under active major scandal, with extensive and ongoing legal and ethical issues, including bribery, environmental destruction (deforestation), labor violations (slavery-like conditions, child labor), and allegations of price-fixing and selling rotten meat. Recent lawsuits and financial penalties confirm these issues as active and significant.",
      "asia_tier": "A",
      "asia_tier_evidence": "JBS Foods has a registered entity named 'JBS Japan, Japan' listed in its SEC filings. Additionally, JBS USA exports its products to key Asian markets including Japan, South Korea, and China. JBS is actively strengthening its presence in Southeast Asia, with a stated strategic focus on the region. This includes an investment of USD 100 million in May 2025 to build two new factories in Vietnam, intended as a regional distribution and production hub for Southeast Asia and implicitly, Northeast Asian markets. The company has also operated a leather plant in Dong Nai, Vietnam, since 2014.",
      "industry_primary": "Food, Agribusiness, Protein (Meat Processing)",
      "industry_weight": "High",
      "company_size": "Large",
      "employee_count_estimate": 280000,
      "why_it_fits": "If not for the disqualifying factors, JBS Foods, a Brazilian multinational, would present a strong theoretical fit for Wendy Higa. Her native Spanish and conversational Portuguese skills would be highly valuable for a company with strong Latin American roots expanding in Asia. JBS's explicit presence in Japan, as listed in its SEC filings, coupled with its significant strategic focus and investment in the broader Asia-Pacific region for protein production and distribution, aligns with Wendy's interest in Tokyo-based roles with regional scope. Her cross-functional commercial background spanning marketing, operations, pricing, and supply chain within multinational environments is highly relevant to JBS's extensive global food processing and export business, particularly within the 'Food, agribusiness, protein, beverages' industry which is a high-weight fit for her profile. Her experience in B2B contexts and managing complex supply chains would be beneficial for JBS's operations in developing and serving Asian markets.",
      "confidence": "High",
      "confidence_reason": "Robust evidence was found for JBS Foods' Brazilian HQ, the existence of 'JBS Japan, Japan' as a subsidiary, extensive Asia-Pacific operations and strategic investments, and global employee count. The classification of 'active major scandal' as a hard disqualifier is also well-supported by numerous recent sources detailing ongoing legal and ethical issues.",
      "role_archetypes_likely": [
        "Business Development Manager APAC or Japan",
        "Commercial Manager / Country Manager Japan",
        "Supply Chain Manager / Specialist",
        "Trade Marketing Manager / Specialist (Asia, APAC, Japan)"
      ],
      "flags": [
        "Hard disqualifier: Company is under active major scandal (detailed in 'out_of_scope_reason')."
      ],
      "suggested_next_action": null,
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF2l4HMCnxPe6_adW1ng8x4WnD0kuu6r_weKoW1ydcCUxpL7mWWJVukszd7v77Ra1qzNxYsfQ0FpjaPid3LnXVwq2i6GuvCDYM6mMCqrKUzkquVFKL63xRt-Hu9-Qv5eRVb",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQECHR3VdTuT8LwFDer0yvRH20HAoEAyY4rCUTmaPdRy9NxHO-JlEmVBYKYtDshgHpHukPSBWOcTdb3J4YZBvrJe109eomx5E-xOO6an6OYvyA2yc63qNjgFbkHwiGtC_1k-sh_oo2r1lAlgEe6dsmjX1nEr0AqO66NxhnUOR6HJ_t9i0kdwNU4=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFO2JqwUHRx85xF-T-8UEN40FRVYI-re7ySKBEkCELxRIRTTY4gFDVvavWLxke5iCfZMU0DMRICiIp3k0fu4wiN1imnO6h3TW5eP8g2pDRXDxHcTCi7Tm34D0XJEHF6XIuW6f8b-Q==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGkfyy1q-69H7Dp6hKz_b2MaEMbQlR3ebzpy7yn4WrGvZvmfF_w07QPBBHvYhja-M_vVz8ypRSZodYsrC7NClbHWK8Zvr3LUwr_hFfwvNMSEzW4-_uKvgy2skvLoVQaVjIkRVcrvQGS2hUvOjpHhg961z056aO-w0TnhdrVz8AixjRYoj5AdLkOFn8A3oX3cwI_ODnu-IiInuyqVAfBi-w=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEo3YmYaXSfqwl2ZkY0Q5IJNcZb33iFBR0Cd1koIK2k10EkxigkNV4P-onuhRrlWUBpObSYnFMab3W8jBtsG2ITFYPU1b9GiNPKc9tWg6q2kIbLvRu6BWGSssuJzMfn1xb6QNZasHZfKh6l53VdqiDE5a46cejUQxxMnw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFf4jq20cuMsnhQF-GyggDSYOAK-cUNkDCOqBkM3_qS7SgVA_gJY6oSUGm0hptOiKl9SD-F1ITViRsQZ4lL0KSAEJ5hKYlMTY0uk7oCQVSJ0zW1rVjLlNXiVZm5Yk6hGqDzB5ZtMjzrEu1d88I=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEUYTg357yt2lxJekW8LGsjhShQHp9xG8XxTraVT1vmi_riWcwvMkVxPPGOVsG7SB6YZDWUmCWPoSimmPBiwD2S0e2q8LogrK4XCJNRVT9Y4Em0dqwzx5jyIR8XUqriK7-MvNQ9UaKoLu6D",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFDbbOPO2jBsEcXHC1wdZnOEP_nsZ567ReyKeYqyD6HhbOFD0atXnTqyoNbyY67jLyEPsqzRBIGMmAzM-fWgC56U9F8Ilo-VIiM7x7aFlEyq8R3SCwk_T2zXc8j1M9FiKy-HzH-NK7JaJNfmN6iiaPXS8doaHTqOIBWgk-HwnGLBWnC7ljAerGCtosH4A==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHdidUBE6ihC0GlwQatYcptm6kFOSAkTL8kWI-tKO3La-K25e6Lkr_To9v36Ly-TtiEf52zTzuzbqwd5K5qb1yRsg9_fOW7CSgSkr584FqWbu36paBn1b8w8HvCA_Q97gzem9gY3CmEvQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH2781-5T2wBikLko7RSn3pnHXZQwsfqtnti_xmsgz6bm45mbVTjBjgipY55qPWO4NzF3Zbd2uref77rR6D9lOniy34goriAay5GKhDNiiweLpEMOQXawm1YYFbeLD8TFXTpHrlp1uqXup5Wi7-G-2rl6UE9Djp7g8ona8epERL7sZ708U=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE_S9XS6FnGIYrQ9wnd3WQbgVKdKyA3xAtf9F6eqPjlk84nOgRD4qiU7DrXPYb4rZ5N5gYpgxjzgpGyg6V_Pxlkz59OfXMXsmep0G2LzKNQmVjKODMFbbVRoemV2yBvAqvEiSuOP38PrsQFnSr063Dfzt69XF66w7uTb9FCKvZEp6b_zBXMh72xOYfnYhJVEsTbyZzik1ZfteehE3LjHAUtVsFGaKT5HA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF0GtG_YYuOG2vk7PTLKzAZ4dozT1QZFvxTwOddnCye6GjCJlFo3YbRmx3elbaYkdC_pOeg6ns5B13nQbe3SUltSyuG4FMraLb-L3iFckq_mEJOFZa427Ok2k-4CFpeeMz1DTyWFyTl7gkL1xctNgyYbDJD2Vu2qNRkCFlsQ1awmqCLXHLVJgU1t6DiucwsR7BylvM=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE4DznI-GibBJL0vBc347ZdOoAXu8YBp_7d8zGfaSI6TIkZxS9DmHfzAOoN9Qxlbxxcq4kLdvndN3ak8eQEGnnQO9L0L3ct5U0FKairakgdXUkbMDDBjxaacGCPouc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGNMuyTGKlDCF-LTYI8n5--Z8xtPbKkAJ4jce0CAJAlF9syuNTkNCmzqGNGECEG1SvAV0IhBL_F6nuE-cHXuNLgmh-BJbQQi2FbiXTiYg3A0DfiqSDT6sHTa-6wi_rIDgIEe5sMorXxZEo5ZtBp7qmDtx7-vPRIOYuoLLMBlwdKcezbifaIHLhmws78rM-A4m882in7ngN_6BVel7cr8FrVRN_zTsY=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGucCLryr-aOocoMxaJUE7ZLOh0R-x_ML6F67k6b7Gl73L6YL2SxJyGQqMThMp4Xm2ApUunJcXkF-dnPpmYfSyVp4CrnokQ1ewf78CzOa62wqhfGQ4AO1W42Aeo1Zb_UVDIgUczmVFtdQlQM6odXn3mFYqAg7lIl2NwJQZWFgc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEk6h7a2B7jIGzukf1A0FmqNI8njdTazKv8KKqIU_5CWztyh8KqM2cLN9bu3edtXFo3N9AWv4k56tUJSku--HfconQwRvbqRL54GMXKZL3pBTfyHhCqw0rQjsMYDQNJC1HkOzoiOyJCeWai4C5deJCvv4k7",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFC54nyxMwTVxQM_Y55EB-1JJl2s0ui7QZEOVQ_IaUVS_4M-85pMqfwJpT42dbEp7kTQDJcDCn9XTiS71oCKVkepRB-T82FgRzzOdfwMKWhm1KSQ0Ra6GGIFj-istAhsrFxvnj3uUVZ5g==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEgq6JEAXiWHcZG5hcQB6iQGehZJ6ZQXETmH43qO7f5emo_PdrDA8s2aFpIyjdZqwCye_wbxgk4ex537TAJ17K82EfRhRipCNwds1PVsnAAz0mLDtytfy1ipHxJW7TurSE5aQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHgO61OFhh5X9m1C9eT1llR7eZJpD3dU75bejktTqP3WN2IVGRSS2RobZYs9JtW0nQmWizwAxYfgbouPdSVTCMbKnaOyozrvou0gmUCeg0Lb7FlX1zxcysBBul2Fw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGEK_bzBu7Tlb8QdHd5xd5jyWONR2D8alxTorWZsjZ7UYWqib7lqReo-CNYJjGNEuNlxv8JlA8Wb3P6OiMhM5ZLTDN7FnusXN-4BamAvMxtDtA=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGS3xnyxtmAN_-IiyXdJCII0T64-TV9-2Dg7Fo8SzsT7ZwgyTEAPA1yquoQuG5T-vcW16NujrXacgXcgRTLADrzRkkBCtQUKDEcLCKdfotGHUDePTfajW9m3d7CUPhtZXNV",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFQ_N-rCydM67F0N8x_1tQ9wnd3WQbgVKdKyA3xAtf9F6eqPjlk84nOgRD4qiU7DrXPYb4rZ5N5gYpgxjzgpGyg6V_Pxlkz59OfXMXsmep0G2LzKNQmVjKODMFbbVRoemV2yBvAqvEiSuOP38PrsQFnSr063Dfzt69XF66w7uTb9FCKvZEp6b_zBXMh72xOYfnYhJVEsTbyZzik1ZfteehE3LjHAUtVsFGaKT5HA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF-OhQLflyD-uUb1wBQ-uxNZGSh3ui_HyjNROqhPVg7NL66_m3waiGT_rrpjxshaWRdw6nPB_LCqtj5bOJX4I0KMKAxN2-4Ib31MWUveS44ESa_mrhIuIq_eUlU043hRfLjw-aTpI1ODEsX0w=="
      ],
      "search_queries_used": [
        "JBS Foods HQ country",
        "JBS Foods Japan office",
        "JBS Foods Tokyo subsidiary",
        "JBS Foods Japan entity",
        "JBS Foods Asia Pacific",
        "JBS Foods Singapore office",
        "JBS Foods employee count",
        "JBS Foods LinkedIn",
        "JBS Foods Japan news 2025 2026",
        "JBS Foods Asia news 2025 2026",
        "JBS Foods Japan Country Manager LinkedIn",
        "JBS Foods Japan hiring manager LinkedIn",
        "JBS Foods Asia Pacific Marketing Manager LinkedIn",
        "JBS Foods Asia Pacific Business Development LinkedIn",
        "JBS Foods scandal",
        "JBS Foods Japan downsizing",
        "JBS Foods financial troubles"
      ],
      "verification_gaps": [
        "Specific details regarding the physical address of 'JBS Japan' in Tokyo, the number of local staff in Japan, and a direct LinkedIn URL for a key JBS Japan or APAC leader were not explicitly found in the web search results."
      ]
    },
    {
      "company_name": "El H\u00f3rreo Healthy Food",
      "hq_country": "Spain",
      "in_scope": false,
      "out_of_scope_reason": "Company is inactive and underwent insolvency proceedings in 2020. No evidence of current active operations or reported expansion into the Japanese market could be found.",
      "asia_tier": "D",
      "asia_tier_evidence": "Iberinform lists 'EL HORREO HEALTHY FOOD SL' as 'Inactiva' (Inactive). Furthermore, no recent evidence (post-2020 insolvency) was found for a registered Japan entity or an APAC regional hub for El H\u00f3rreo Healthy Food or its successor, BIPLA ASSETMANAGEMENT, SL, regarding expansion into the Japanese market. The 'inactive' status implies no on-the-ground Asia presence for the original entity.",
      "industry_primary": "Food, agribusiness, protein, beverages",
      "industry_weight": "High",
      "company_size": "Small",
      "employee_count_estimate": null,
      "why_it_fits": "Based on the initial prompt's description, if the company were actively expanding into Japan as a Spanish sausage producer, it would have aligned with Wendy's commercial and cross-functional background in B2B and retail, and her proficiency in Spanish and Japanese. Her experience in supply chain, marketing, and negotiations within multinational environments would be valuable for market entry and distribution. The 'healthy food' aspect is also a growing market in Japan, aligning with her profile for data-driven marketing and commercial strategy. However, the company's inactive status makes this hypothetical.",
      "confidence": "High",
      "confidence_reason": "Confidence is high because multiple search results consistently indicate that 'El H\u00f3rreo Healthy Food, S.L.' underwent insolvency proceedings in 2020 and is currently listed as 'Inactive'. Despite extensive searching, no current evidence of active operations, a functioning website for the food production unit, or the specific reported expansion into Japan post-insolvency could be found. The lack of current information for the original entity or a clear successor operating under the same brand with Japan plans strongly suggests it is not a viable candidate.",
      "role_archetypes_likely": [],
      "flags": [
        "Company is inactive due to insolvency proceedings in 2020.",
        "No current evidence of the company's reported expansion into the Japanese market."
      ],
      "suggested_next_action": "No specific action for this company, as it appears to be inactive. Focus on other candidate companies that are actively operating and expanding.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHvo2RViVkHcDATA7GRI-P8Mquq9iRwGoR8tpH-Cp2O2ct-26IhOWyZ5OFOL9NTwIuYVwbc2ANV7-AnnXO_BLYnTUYgyacXscQY1qh5gdHlKV3VWf9NnPCpTq1-SRYhHfecawR0RbsM6N8R4MG3uH7P1_JpPhM4mHcbFV9Jx0SJc8MAvaHtrllZzrM",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGsuFMCye5OndlKbdJWidjktESTzOJcHO1x1iU8XUrSnJ3MxT29MTGL2c85ttQS9q8UorJOTXzIfDkpk2hmJeKtVTQGdaoK3FwKoHQ8deYAjpzXMs81C7TM3EzZsiuy9HZkehHf824OZrMCklkfIBgPEfKSkuSmjPprrRaHopxh_PzK3c-htfjJzMemG4A",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFMgGeFjkI1Cz_1-4ReAhNHVA6NMLI7vcNlooE9psIOMt0oB99j1Y3_eEMw4BAj70bme9MYHhSRgbzFTVp2e8UCUt4sx0I2yA7Q4uzt2PFj01342Cy46_2Ss90RS5bIfxRfY8a12T2rvTQpQTU4dzIjfQda9SW-AF81I9Q",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHc8ZUnrW4x5HG7AB_VwCz0U-wl1IEHMiymFRb1R9Alqz6b0zo4NnUAoxp1P0jaLjRyykDC8XjlV-5KH8WloU0BCGVzF8vyqu-xsWYKjl6u82xoyOSmxF1QUFRz0jhXpHPSd7MuBLGyLqypc1gMNJbMkYDeCwolxviUsXTopIXRY-6BxHMglujQhFnlgls8exDycA",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEJsxWUULvK8Qx57ROnFo-jfCNGZphKo6ylsiDolCFg1jUOYWXsZbO_b1du3mgwSaO4e1RqWcO-DHv7Vsf0swuI5RchJzTi_grtYEN6GMkByi57OVKs7Mo_OQ8f8Q4tc2LmnPdiGKQkuKF884e47M42nMDVb5R051CgQpI_9qwM2RmBb04iX-Fph8aVcWoKm2pDjbfj",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGUiKDM73AIVkuxBIVis8Dvfp6pkbXujt3hh6zIgpfF4P31FMSc1XxuoCbvM013dWZb_3PMdG2o_3VMlaytkC-k-qjKlCjBVjqKnDyBGqOthiEdpoV8mIduyYI=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFpVS0q0gENTut6mChQI7xic5TlFIGev1oiuo6aA6ywlIZeysJW6HYIiLn9OxD_m6iDIXskIA44hR4MOxDyizoyWO1otucSikps5CeCBdjfS7CFFewekkAj3c9FJJXO9IucMYJEwK1_MzgHrRh_U9HlkNl0w70"
      ],
      "search_queries_used": [
        "El H\u00f3rreo Healthy Food Japan office",
        "El H\u00f3rreo Healthy Food Tokyo subsidiary",
        "El H\u00f3rreo Healthy Food Asia Pacific",
        "El H\u00f3rreo Healthy Food Singapore office",
        "El H\u00f3rreo Healthy Food employees",
        "El H\u00f3rreo Healthy Food LinkedIn",
        "El H\u00f3rreo Healthy Food Japan news",
        "El H\u00f3rreo Healthy Food Japan expansion",
        "El H\u00f3rreo Healthy Food Japan press release",
        "El H\u00f3rreo Healthy Food scandal",
        "El H\u00f3rreo Healthy Food downsizing",
        "El H\u00f3rreo Healthy Food reviews Japan",
        "El H\u00f3rreo Healthy Food Spain HQ",
        "El H\u00f3rreo Healthy Food current status",
        "El H\u00f3rreo Healthy Food after insolvency",
        "BIPLA ASSETMANAGEMENT SL food division",
        "BIPLA ASSETMANAGEMENT SL El H\u00f3rreo Healthy Food Japan",
        "El H\u00f3rreo Healthy Food Japan supermarket 2024 2025 2026",
        "El H\u00f3rreo Healthy Food press release Japan",
        "El H\u00f3rreo Healthy Food official website"
      ],
      "verification_gaps": [
        "No current official website or active social media presence for 'El H\u00f3rreo Healthy Food' was found to confirm current operations or product lines after the 2020 insolvency.",
        "No specific news or press releases (post-2020) confirming the company's plans to introduce products into Japanese supermarkets and delis, as suggested in the discovery phase."
      ]
    },
    {
      "company_name": "Logisber",
      "hq_country": "Spain",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "C",
      "asia_tier_evidence": "Logisber has a global network of specialized agents and operates in over 80 countries worldwide, implying an active commercial presence in markets like Japan. While their Spanish website lists a Shanghai office, it does not explicitly state this office functions as an APAC regional hub specifically covering Japan, and no dedicated Japan entity or office was found in the search results.",
      "industry_primary": "Logistics, shipping, freight",
      "industry_weight": "High",
      "company_size": "Mid",
      "employee_count_estimate": null,
      "why_it_fits": "Logisber, a Spanish international transport and logistics operator, aligns well with Wendy's profile due to its HQ in Spain (in-scope geography) and its core industry being logistics and freight, where Wendy has direct experience. The company's focus on international transport and customs, including expertise in sectors like food and technological products, resonates with Wendy's cross-functional commercial background spanning shipping, aviation, and B2B technology services. Logisber emphasizes connecting businesses and cultures globally through its network and multiple offices, including one in Shanghai. This global outlook, coupled with their stated experience in shipping between Spain and Japan, suggests potential for roles that leverage Wendy's Japanese language skills (JLPT N2) and her experience in cross-cultural coordination and international B2B environments. Her ability to bridge strategy and execution in multinational settings would be valuable for a company looking to expand its reach and strengthen its commercial presence in diverse markets like Japan, even if currently managed through agents.",
      "confidence": "Medium",
      "confidence_reason": "Logisber's HQ and primary industry are clear and directly align with the rubric. However, the exact nature of their Asia operations, particularly regarding a dedicated regional hub covering Japan and precise employee count, could not be definitively verified from the search results, leading to a conservative Tier C classification and an 'estimate' for company size.",
      "role_archetypes_likely": [
        "Trade Marketing Manager / Specialist (Asia, APAC, Japan)",
        "Business Development Manager APAC or Japan",
        "Commercial Manager / Country Manager Japan",
        "Pricing Manager / Revenue Manager"
      ],
      "flags": [
        "No direct Logisber office or registered entity found in Japan; presence is likely through a global network of agents.",
        "Employee count is an estimate as precise numbers were not found in the search results."
      ],
      "suggested_next_action": "Message Pablo Bernab\u00e9, Deputy Managing Director (specialized in Chinese market) at Logisber, via his LinkedIn profile provided on the Logisber Team page (https://www.linkedin.com/in/pablo-bernab%C3%A9-b881335b/).",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFXawmJw_NDpN41UujsJP0iJPhXWNLmLalIehl_BDjzGtMyyNCAnevf0CGRQWhbHQqqZYP45Yb3bD78OhIkQoYt4Wd7LuoKTN0k-0QocPPYK5Wb2vMuuU1U",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFLIYaf4pkfAJWsU4N8dKdy-FHt-g5Ijs9qmSBCWn4nWaloy0zm9H3LaGDRCTLGmKBNj9xHZH-DPfw_Lo-_GaOv5jl5SHQ0myRa66eHe3QkCKs7Zz1Q_WmwoyuaqhJ7eZraHv6GShyTZr25Hw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFLcd36RAg-6_GenkMAsujzJDpu5DILpUa-_rfgtuRpGFn6gPPml0tAPftPpAE0I680pwGq65DgXYXXR5NtNb9nhbDaiGP6UIUHxhnl7-N2hchpg4crDjf9Eiiy10IVNJxWatpHxReuN-Aucg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEdQjb70kuSCxhKevMkbaD5LfAYm4u_oN31OBbUOV-ZmxF200kXuggS9l_jM06mvfKUE8QwwC83XV87qjUuCEHYi8q9t-krPS27AwcLFm7OWRUZFKW0HBwaZAxxLW7SPke5rvNsHrRMlpIAFbJZUTCgEYQj",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEdgODBYZWU_X9TGbmsU2mbI3O6xh0MYN291am46W4v8uvH4OudbiegRNQ9EBBFJkKMjVK3vA_zON7ppjhUG7SwerRVsabmMCDXH1GOzD-QyX3UsLHf3aUnz49L",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHWRvrFSiXqz0LGvNHvyFnH8oj-p2BYnN2Nqjmo1zKFoNG_CU3D-09cDDpmGuh7CuTlKGD9IsYJ7SknYFL-M27p3r4feSd7QI0Y2KLA5Hh69DYoN9luOx8MNPfJPLc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF6YLvFmScB1ygRPbsVT5kgTp78jKsZIaAq_H_5m3tBsXMeu49whiHDzcP7Gatl1NsCQoiyspCv_BDhRt907QxhHOtvYKdye7Wb7VwU2gKa8v1b16cRLXtfo0crlOdYTP5o-Q==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFK59zEyolpIRCP6cIoYj-2BMcQQtcLq3GNw61X5vFFL4JZrh75ORpOzj-wNiMyId3wMBihINrSHmO24HhsUA6fV2g8As1zuZdbqRYNWZJ07-oTQ5-vUaNm8lc7V9oq-0ve9caz5WCjE5Z1mNH_AGqQoZ4gwDbejTpHzqY=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFBg32dLHN6ftU-Md8cpNRFahHO46775txp4yUisBwt8hR0htDa6fbLVlLNlovhqaKBqtyI9saQqNJzCIEuMbACf1Go7Bs7Rm-acC4uIIH4LXbdK-aLZ_vG",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGqeO05q43usgvlJGEk616ahtBVimf102mQ4eBFv3HbkNpSmEcJWLg4k5WKLYxKNGmOlxEr-ixGlXsKGuxBp266BF_clW1vLr3oa0A5vwpaL44aL1OLerVclw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQERg8g7zrbZrCk8zZF9vtS2gyts74_xBCqHR_Xob4a2esbdrpzCbI2jG-tQw5yFtXLYnn1A_sqkp95h_dydjuII7x4vU31NjT394nK0SfFqsA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGnnUQwWbnLJiMYg-YgdCKs88mHcrmQyX0O0aLh75plKEAfj05xaP8OGqu62CkWzAlsz3TNWBy1CkdWtRBF6CuEnYHadxMF6i4jm1vo6Ymv0Y2mS4lJ766h35SCvvCZbWAbx52Avfd7ejXlIC03Pen_",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGFXtrLwKXLGVpwOwdqth2wHiMLgL_T5ZdaBulmmvKOZ_htIz57Iiz53sPfd_86ndTPVU9-OMoMPE8dSHO_0WQ6WDHF1b4Lt8pyvi_aZOLj9JpBnnlmuDrlY2jugW0FwsQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHutc11XVOdibbUthXELmt_fX8_DkORP5XudbQKD4N0H5SD9yUISts_WgGAqvDxQVzQSrs4_bCJYU5ssNKhGidPFHRitoDxTr1Cqum4dMh4k6_UEsbs",
        "https://www.linkedin.com/company/logisber-forwarding"
      ],
      "search_queries_used": [
        "Logisber HQ country",
        "Logisber Spain office",
        "Logisber company profile",
        "Logisber Japan office",
        "Logisber Tokyo subsidiary",
        "Logisber Asia Pacific",
        "Logisber Singapore office",
        "Logisber employee count",
        "Logisber LinkedIn",
        "Logisber news Japan",
        "Logisber press release Asia",
        "Logisber hiring Japan",
        "Logisber scandal",
        "Logisber downsizing Japan",
        "Logisber key people Japan",
        "Logisber Managing Director Japan LinkedIn",
        "Logisber employee count LinkedIn",
        "Logisber LinkedIn official company page"
      ],
      "verification_gaps": [
        "Could not find a precise employee count for Logisber.",
        "Could not explicitly verify if Logisber's Shanghai office functions as a regional APAC hub specifically covering Japan."
      ]
    },
    {
      "company_name": "Molino Campo Noble",
      "hq_country": "Mexico",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "A",
      "asia_tier_evidence": "Molino Campo Noble \u682a\u5f0f\u4f1a\u793e (Kabushiki Kaisha) was established on February 7, 2024, as a registered Japan entity. The company operates in the greater Tokyo area, co-founded by Geovanni Beristain and Reiko Matsumoto, who are based locally.",
      "industry_primary": "Food, agribusiness, beverages",
      "industry_weight": "High",
      "company_size": "Small",
      "employee_count_estimate": 20,
      "why_it_fits": "Molino Campo Noble is a Tokyo-based tortilleria co-founded by a Mexican entrepreneur, Geovanni Beristain, and his Japanese wife, Reiko Matsumoto, with a mission to bridge Mexican and Japanese food culture. This strong bicultural and Latin American connection within Japan aligns perfectly with Wendy's profile as a Japanese national with native Spanish and business-proficient Japanese, eliminating relocation or visa costs. The company, established as a Japan entity in February 2024, is in a growth phase, expanding production with new facilities and machines, and actively supplies both consumers and B2B clients like restaurants and culinary professionals across Japan. Wendy's extensive commercial, operations, pricing, and supply chain experience, spanning diverse multinational environments, directly fits the needs of a growing food business focused on sourcing, production, and distribution. Her proven ability to bridge strategy and execution, coupled with her B2B background, would be invaluable in supporting Molino Campo Noble's expansion plans, including their stated future goal of sourcing and distributing a wider range of Mexican foods across Asia.",
      "confidence": "Medium",
      "confidence_reason": "Strong evidence exists for the company's Japan presence, founders' backgrounds, industry, and growth trajectory. However, the exact employee count and direct LinkedIn profiles of the founders could not be precisely verified.",
      "role_archetypes_likely": [
        "Business Development Manager Japan",
        "Commercial Manager / Country Manager Japan",
        "Product Manager",
        "Project Manager"
      ],
      "flags": [],
      "suggested_next_action": "Search for 'Molino Campo Noble' on LinkedIn to locate the company page or profiles of its co-founders, Geovanni Beristain and Reiko Matsumoto, and review their backgrounds and any posted openings.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH5ace6LPG8SAVizMW07jqDnTMH3ai4rGZOf8ImyYktKSLHgNFIZ3kQ5UiiUhFLlXgHfAi9-jR1ecBIgBDVTo96Sk2FGNEhAC4FFSR5dNGGeTWLNKrP8a3Q0uMPhwuFF0-D6DruTz739RG26PkcVDyg-uPa1g4b060sNZVchH4RZOVIbxzqmPCOqUtPIhtM2KpVAq4Utux7zR2YLDtG_yW4Ha_8oYoVKjlPVw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEHQ18rV87_RT7nAWj7RSd7dGVconFC5PxPFiwZrzD7ANauI4bAU7LfPIH8e77IZljx9I2fUxOV8iBdjd8Ws8nG4RJOagJ9sGB3CQ76TTpFtaeVGQ-i9EOFw_RCl4h-yo3mBFCJ0_cIehFmY2NBU5S-RLMglRioaaQ5cPQT-cdqIpkxtThsEttL9p9UuBpwUxY_ZA2xKi9eCtOakG2ydLiZyWqaInk=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF09bhdrOdKDD6M9lhhkKZGGl-7Y7YX3G6kkUzVsDd4MP8ESDh1qM8IIxzo048J_CPODenD6KSr6xV_2jLdLZYDQF8ppkNK5b9z_v4udvhFketo3clN1FQf7o874POfFTrq71jkLPZOTMv1C3l3",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGWLmI6XYDWEUGWFC-3NsbjalY2BdC4UCdjyBRmUN9Ze68fZ_9AX970IxHd4CtUHyYJ_PhL5bK3wQGH0sVrCEKJk0BtM7VqDSdQMHpkjPZ6kAAja5Rpk0Lbc18VD8DzB-VsDfhcjY3l",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHFmj_bLj31nCnyQWWy410lhqaKyRCNJFra2z3fl1dUAhNq5i6Pum1NK8ai5xq7MvduO33FO3NhQW2s78eUh_Uezze4_5uK7-l-y6qUgx_3exdLnE2QVqGSQWLCEkbC1nTksNqNAA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGFvH75IYEPx2n1o4-jEISfFIJAajurPiN3jBs_xBm47NEWIx7Ob0zg8iQe4TAxVFjp7eVBPy-5xtNLFovO5tqkj5wAh-ZP0EBDbvEo1cv2I7coUCrv1-JhOmLw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH3M2g4BGXYYa_NbScEQkWAGhhySjLepb3Vx1F1pIS_qmhpW_NUoP9btpAqke_P2m895rjZBEEynjwPIV0etcaWoINtwEH-jG71BTBoiDaaMzP66Qkcebi_XphTWqk8RQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG89j-2xkb0tkTalCiv3OR0kThXB8YRuThrC8XZipKAcmxL5AqccawPr69lBp5sEtkA3xl1mKlEs36Xg-6FKWkfB2CtvcMs39z8ozn3R73FILBN_FycMXXRBf2lGUtZA-PCMtofhU2cmcY5",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFEaWGe4pZ8yOlgFlyFsJQ9NjSmIRk-pDXzS90Ze0rY28G0rAOtLFWc8JGlznlzeCU2aas2FZa4PwdvghXaXKviBhCCtP0TJR3QVm0QODstdfhyhJfXN5sdkxoCSodK2z7OrU3Yhq1-JUsemDZymQQuShGibQ8Fk2xgUwQp",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHp3ghKh6-CNGrcCURVWyStFyrFenQHvFTjHlfysBqyh_gvzKey5YNvX6YxtWpwrMq2TJmjcF3k9_qfm2bginkmhrzIYjMEjWHx36sfQ-lc4qGuq1uQ8jr3",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGkXRrDooDmOhklwZUgdKj82ZoHcEBsXwlGPFPkaCKo70v-qDyCBP-RBILuLmaHioqfKjIy39sS1bSiX3ha9YazNYL8YhoRm3WswRQdmp0qN0ULAmy0ZUUWztDn1Dk="
      ],
      "search_queries_used": [
        "Molino Campo Noble Japan office",
        "Molino Campo Noble Tokyo",
        "Molino Campo Noble \u682a\u5f0f\u4f1a\u793e",
        "Molino Campo Noble Asia Pacific",
        "Molino Campo Noble employees",
        "Molino Campo Noble LinkedIn",
        "Molino Campo Noble Japan news",
        "Molino Campo Noble founder Japan",
        "Molino Campo Noble CEO Japan",
        "Molino Campo Noble scandal",
        "Molino Campo Noble downsizing Japan",
        "Molino Campo Noble Tokyo tortilleria",
        "Molino Campo Noble reviews Japan",
        "Geovanni Beristain Molino Campo Noble LinkedIn",
        "Reiko Matsumoto Molino Campo Noble LinkedIn",
        "Molino Campo Noble LinkedIn company page",
        "Molino Campo Noble employees LinkedIn"
      ],
      "verification_gaps": [
        "Specific employee count for Molino Campo Noble.",
        "Direct LinkedIn profiles for Molino Campo Noble co-founders Geovanni Beristain and Reiko Matsumoto."
      ]
    },
    {
      "company_name": "FollowUP CX",
      "hq_country": "Chile",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "A",
      "asia_tier_evidence": "FollowUP's Japan operations merged with Data Section Inc. in 2019, which is a publicly held Japanese company. Data Section Inc. explicitly states its headquarters in Tokyo, Japan, and carries out activities through the Japanese market, indicating a registered Japan entity with local staff.",
      "industry_primary": "ICT, Enterprise Software, B2B Technology Services, Retail",
      "industry_weight": "High",
      "company_size": "Mid",
      "employee_count_estimate": 235,
      "why_it_fits": "FollowUP CX, a Chilean-Japanese company, offers technology solutions for customer experience (CX) in retail, transport, and smart cities, leveraging IoT and AI. This aligns strongly with Wendy's background in ICT, retail, data-driven marketing, and operations. The company's global presence, including offices in 9 countries (Chile and Japan among them), directly benefits from Wendy's multinational experience and language skills (Spanish, Japanese, English). Recent signals indicate significant growth and strategic focus on AI and data solutions, with Data Section Inc. (the Japanese entity) making major investments in AI infrastructure and announcing strategic partnerships. Wendy's proven ability to bridge strategy and execution at a channel and customer level, coupled with her cross-functional coordination skills, would be highly valuable in driving adoption and success of FollowUP CX's innovative solutions in the Japanese market and potentially across APAC, especially given the company's acknowledged 'language issue' in cross-cultural collaboration.",
      "confidence": "High",
      "confidence_reason": "Multiple search results clearly establish the company's Chilean origin, its strong integration and merger with Data Section Inc. in Japan, its industry focus, size, and recent activities. The 'Chilean-Japanese company' description from the prompt is explicitly verified by the sources, and the tier classification is supported by Data Section Inc.'s status as a publicly held Japanese entity.",
      "role_archetypes_likely": [
        "Commercial Manager Japan",
        "Business Development Manager Japan / APAC",
        "Marketing Manager Japan / APAC",
        "Customer Success Manager APAC (B2B contexts)"
      ],
      "flags": [
        "Roles explicitly requiring native-level Japanese for customer-facing or legal functions could be a soft disqualifier, though the company itself acknowledges language as a 'huge issue' in collaboration, suggesting value in bridging roles that Wendy could fill."
      ],
      "suggested_next_action": "Search for 'Head of Marketing Data Section Inc. LinkedIn' or 'Business Development Manager Data Section Inc. Japan LinkedIn' and message a relevant contact.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEtCxnerkfLD1yGEeLSXbGpbO0xA_EiqwGH-0GzcxFJXpoBvzyB4cJ0TMEjRKAAMyikS4ytj6GhWVr0iwWbnuWZxY8oFo1ITWE4x_apNhj2ti2oqmSRgmUZDhAgx-gudouVMJdsVZ2Au30XMnDAI4aNBHAO6TsvHCKxnFRdlpJBw3KCnvKiSE3nlFQDuHXouSjWnrDSYcw0_Wr-1w0WGhTEcIXYaQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFMGZVlyf4OBvPb1keNjXa9-EyLMwak2aq4LaKh2QK__reScw37UEf2Wu6aLzB3rMEeLdEA5UgGLCEDASyk1Ek3iy70rIJfJgLzJ5wTWWru",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHJ28CIDu-x5mN7RXSp3ejqbUQ9QIX8boaVPVxbIMt9Ak_4UPr7GHf93R2gNxnaRMRwrbcmqBghUgOGYAJQ7Yf8o5puXDCtjboVElp5LhR256ZuZUwyphl2eodu6bJvBaINnh-zEyAq-V8uVm4BSgxYvCeX4UE=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGEbjfOgRP_W4TBeEv0ZGwEiPhZY-jNfrIKhGDh8uDzcVwysuWxSlCcvNaruFxs4BRAJBxDsYOm6frXrGdPzK_6X7eKIVixvvLabqI6j62L5Z5MQUC-AClC0AfruG4F1mUvJjGSZvogT-Mo",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEOBYFix_iHwjIHGnMHL8R24zLoE0pEOug6h-rWkxkqDYtM1FgjH9E4YyzK0vGSJ0Ov22JL_B3w17lWmO0U0YW5jDx9w7kkaccqsgmzB-S2IylW5998sN4fMl9qvXojYQUVfSV6pRo7d8ftrJIPhGfiijAoIDFZ78C0Imc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGZrlmkVELszu6T_MkUjHae08FL2S2OmWXxw9Qa7v3UbBAim6MObrBXgIHkeUr5Zhmbc4I8Dr_bQXldGR6Om8ZV4OJc3Ert1d3xPG0mTgLME8jf-a9tzDRzsRFt3wZHVEtKyVfnfWQv21t1vgVa_CCYD84nk1SPWkPAwWcDOF92Qt7Pz1-Xlfu1B_mDq7P5uHWyj5SOaP9_TmtFYyd5qFlP2Qrn",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGDhKK9uYBpaGIGi8MCeN887fxObOX5DMteaC64fwhtjJ9CyHJU6IFBdVBO-_DnVeQBGWjjIs3KzL7zcGI9T_eDVbGK17bwcefxKkoaeTLJyXhk0NOZOaBw9mZY_g1yqXhkKJq_t4VY5Hq4T4akxrDd83dfe74com4QXngt6UO99tzP_4u4UuEuTGRnjA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH1TktZllQTqOrzpYkY18CJjgfYzjPTl8hXsPVhVurXZ3yug0XtiZmy62yeV1EOxbB_tld7ims1vDMLiilU6-bQKgHlA8wjAnpdMDAAyY6wHsLUY-1XlO79ylkAS78wg523DGAG6yc==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG1I9hpk5r-70S-O_MvOtS9WcZwZ-f7_h4piVA6-eaabvDRqcgrQk2mpheOtDcK0aHCbEXOUZMGvbgGaQyntL0Orywdz_ADunt2n8-ZEJGZJPHTzOy5hUJWJMHiHw_JHMKI0yAteie6vD73oHNbALc9UahohsL-h1ClAr5mRZpAOBI="
      ],
      "search_queries_used": [
        "FollowUP CX headquarters",
        "FollowUP CX company profile",
        "FollowUP CX Japan office",
        "FollowUP CX Tokyo subsidiary",
        "FollowUP CX Asia Pacific",
        "FollowUP CX employees LinkedIn",
        "followup.cl company profile",
        "followup.cl Japan office",
        "followup.cl Tokyo",
        "followup.cl Asia operations",
        "followup.cl employees LinkedIn",
        "FollowUP CX Chile Japan company",
        "followup.cl news",
        "Data Section Inc. employee count",
        "Data Section Inc. LinkedIn",
        "FollowUP CX LinkedIn Japan",
        "followup.cl LinkedIn",
        "Data Section Inc. Japan careers",
        "FollowUP CX Japan careers",
        "site:linkedin.com \"Data Section Inc.\" (marketing OR \"business development\" OR CX OR \"customer experience\" OR \"country manager\") Japan",
        "site:linkedin.com \"FollowUP CX\" Japan",
        "site:linkedin.com \"FollowUP.cl\""
      ],
      "verification_gaps": []
    },
    {
      "company_name": "Minibiota Tech",
      "hq_country": "Chile",
      "in_scope": false,
      "out_of_scope_reason": "Web searches for 'Minibiota Tech' as a Chilean biotech company focused on nutraceutical solutions yielded no relevant results. Instead, searches for similar terms primarily returned information about 'miniBIOTA', an unrelated ecological project. Therefore, the existence and business activities of the target company as described could not be verified.",
      "asia_tier": "D",
      "asia_tier_evidence": "No evidence was found for any Japan entity, APAC regional hub, or commercial presence in Asia for a Chilean biotech company named 'Minibiota Tech' focusing on nutraceutical solutions. The search results consistently referred to 'miniBIOTA', an ecological project, which has no discernible commercial presence in Japan or Asia.",
      "industry_primary": "Biotechnology / Nutraceuticals (as described in prompt, unverified)",
      "industry_weight": "High",
      "company_size": "Unverified",
      "employee_count_estimate": null,
      "why_it_fits": "Based on the initial description provided in the prompt, a Chilean biotech company focused on nutraceutical solutions would theoretically be a strong fit for Wendy. Her native Spanish proficiency and business-level Japanese (JLPT N2) would be invaluable for bridging communication between a Chilean HQ and the Japanese market. Her extensive cross-functional commercial background across diverse industries, including food and agribusiness, aligns well with the nutraceutical sector's market entry and growth challenges. Her experience in B2B sales, marketing, operations, and negotiations would be directly transferable to establishing local collaborations for product adaptation and certification in Japan, as outlined in the discovery flag. However, this assessment is purely hypothetical as the company 'Minibiota Tech' with this specific profile could not be verified through web searches.",
      "confidence": "Low",
      "confidence_reason": "Web searches for 'Minibiota Tech' as a Chilean biotech company focused on nutraceutical solutions yielded no relevant results. Instead, searches primarily returned information about 'miniBIOTA', an unrelated ecological project. Therefore, the existence and business activities of the target company as described could not be verified.",
      "role_archetypes_likely": [],
      "flags": [
        "Company existence and business focus as described in the prompt could not be verified via web search. The provided company name seems to refer to an unrelated ecological project ('miniBIOTA')."
      ],
      "suggested_next_action": "Clarify the correct name and business description of 'Minibiota Tech' from the source that flagged it, as web searches do not confirm its existence as a Chilean biotech/nutraceutical company.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE5iuFt2LgR0PEn2SLA0h_sgtsk-xt5UIW2Jwp9qKOtiUsj9hyL4Aaf9EAx8GwvzvqI2FXt73wmDG_ZzYLjSRr5RKLaKcXKB3SHrchJSA-bETFwia0i",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGX7txBwK94B0jV78rmjIPM5dLgBLOzz8odQTTp9IK8qaa1snpcPFKntR4ykiIs7PXY8BiXg5jHxYAYYA2N0syacOK4nh9-vqffzIt4FtpL6EhVc3amaFIyfSPX",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHuOFusyWeKbZi8iqAG6QdXE17kxMJM541ZnmvHofVEO5M44op6mQqV8Qnuui0fp9l2jXqxa1d1U2oFu1Y_8laOVGDnqYWi4O2y1ohuN-rNVH_GA4CXoHCV",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFdX_ncFU1eU0Y5nXc054GDEQKnDEy5VQLTsq5DsZbMhnxYlxNXYqCNtiVLWNzSczqEM4YM5SNHkav-927vvP23shPfaUcHhbc3Czepkom8ZOdbRlsrjbBRoUH1Fe3UzRjoyy7-btQ=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFY0XLT1m1nNqpBCuPLZ1mCp8dplSx3iWQz4qcFUypRczIm5-IR7QYYK3lzTurkgBJZ5Dw8qeiCKmKr_Olx2jSuVbNrVviJBwLAimIESnaxmA4vjxmlwLUI-gQ-NXyxtxismuC3DSc=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE00MW13IDQaRENVXDmNoPPIOF1nER-kts0npn85Nx3I66QHDNd-gBEMNkRGTJ_mpLI8Mfnb0ogyARKtupPXob8mJKDwUtfvkdIVv5CRXjeilEwzcJp3AfxVkJ-L9lHUdzjcBVtu0BdlBg7C1O1-edMAgo0kyY2pfSiHlBb1PaGE4CTGNcWMTuAVX8nf4TjNmHsBzaPJp8cO8GyNqV7lpmoiMobcW4JD4eC4LiVu9FCfTbw254JEIcUgZ_dO8RlJi3jlJXbIZa1QnV6IB8GduDHsHc6nCt2qYZ15mGG2_jn6WdMsI_-XTI3kV_hTce6fNn_ehrl2rG3TtA2oPu7"
      ],
      "search_queries_used": [
        "Minibiota Tech Japan office",
        "Minibiota Tech Tokyo subsidiary",
        "Minibiota Tech Asia Pacific",
        "Minibiota Tech Singapore office",
        "Minibiota Tech employee count",
        "Minibiota Tech LinkedIn",
        "Minibiota Tech news Japan",
        "Minibiota Tech press release Asia",
        "Minibiota Tech funding",
        "Minibiota Tech founder LinkedIn",
        "Minibiota Tech controversy scandal",
        "Minibiota Tech Chile nutraceuticals",
        "Minibiota Tech biotech",
        "Minibiota Tech Japan collaborations nutraceuticals",
        "Minibiota Tech company profile",
        "is Minibiota Tech a real company",
        "Minibiota Tech founder"
      ],
      "verification_gaps": [
        "Unable to confirm the existence of a Chilean biotech company named 'Minibiota Tech' that focuses on nutraceutical solutions. All web searches for 'Minibiota Tech' consistently pointed to 'miniBIOTA', an ecological project, which is a different entity.",
        "Therefore, no information on HQ geography (beyond the prompt's guess), Asia operations, company size, or specific roles could be found for the company as described."
      ]
    },
    {
      "company_name": "Vicentin S.A.I.C.",
      "hq_country": "Argentina",
      "in_scope": false,
      "out_of_scope_reason": "Company has been under a protracted, high-profile bankruptcy and financial scandal with accusations of fraud since 2019, which, despite a recent ownership resolution in December 2025, constitutes a hard disqualifier under 'Companies under active major scandal' in the rubric.",
      "asia_tier": null,
      "asia_tier_evidence": null,
      "industry_primary": null,
      "industry_weight": null,
      "company_size": null,
      "employee_count_estimate": null,
      "why_it_fits": null,
      "confidence": "High",
      "confidence_reason": "Multiple recent search results (2020-2025) extensively detail the ongoing and highly publicized financial scandal, bankruptcy proceedings, and allegations of fraud surrounding Vicentin S.A.I.C., firmly placing it in the 'Companies under active major scandal' hard disqualifier category of the rubric.",
      "role_archetypes_likely": [],
      "flags": [],
      "suggested_next_action": "Not applicable due to hard disqualifier.",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG7XLavzp3axTAQM-rtWR3JiTro9Kfvucorz1F3gqx4seVWhhmBAjLdeCq_R_ZlxlYx3sv4WjS277CEmYy_fkDx0LHswFwA8Du0Me1Cc7UcADh6IVV7RDmf5jDezXrAz_9htug0oZpblA-NDznL8HScLNN1hI5wmg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHQl0qXqVWxYKOgKgK1mC28G2heE4Ly05oENgD7uHXsCRwBznCSvy3yFZ8QyL34wfIVs7_yNuYes7KaV1iRwC0Xt_ys6Fq0Wqr9GUfHbTHm-tEGCgdioScKUEcCTtqMgfnORGvWBzPpQOFljqV1gyJWApFJLCS0OPE9JhNh0YAthCcRz49GM0OYSW6yFS1s6v3SWpLuUu0BSoA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHbCVGIvQZ__CDrXXMnx4RBMhfEAHeOMMUA2Mp69i6hoau7v2xQwZyV2WxSYg36ktPkHyVm5SS7tVbmGxnaxzEdIbupS0DGVG_a3Czn3Mpf6N20oYNRAejp16C080Y1Idl7Ibyv6OlXLTzZHkB4KsenuFCO4MQ0p_Dh_DEeTa6nHHkhuHfbVthK3eTEbv0R09RttZpofI4up9mlw03_eXPrhNR8COxOyw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF_jh64TchESbVrgnOqOiOCsOqPH-tze0OzhrE79lgRtT3orABVUWtu7ova8aZru-0ujwdTysWQsIXi3IHVHfu2_n0NGOOSFNu4YFPVUIN6qe0sRIVuLxmg-SJZcrdGer-hzJyqNba2QZXmL6ej419j3PsWC97PBfooHzf348S4PAIktal4VaK-bvVnClxahNTcUAEVlAU9sFiVTf4gJaEQoBlf8gnCwqNIspcyYsjPhlZQmENg0DOQHnt0ga4==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFrOmAR3h-pYMlZJd0k2PRgKTiQjXgnw_6_JpOay0F72cftWNoKhD1iM-iblsqXDNWJFpBPN3v1v9MNnG6Acwd2UOjV_H2AW1dh74L01F5VQuHQ_-B7-e1_fSTV4-tmx3ENIBiE2HsAe_NpHNRN4GIv5r7zzg402vymQB7tK6gn-Uq8ak4DJB4GDp3IGMSpePaRqKCwOXMlHlhalvxiCHvzXcev_yHTZA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH95y1VmxbcE91AERZrqJk8L4ghM0KdhgZsciNwiGhumd7eyXLrEDrusi-RXqdJ8nCHSWo_hn7TPpFvgA0ex5dsyiX4nIPisVCuBEGoNXPabCrgo5Zn9mcZJ9odGdX3Rqo_o8_HtuNngBtGB6oRK9rpu5hdKUy-CaJjnTtf13YM9e7gY627_-dRsu74Naa-L2lw9-vGQqusKwNAHotycy6xxTzeyKECQA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGqBb3jwn3huIyQgUJcfJDQErFZj296Cwv_QFTuc1iouFIQuU0v4ZKA2eLTbCT0aCS9BnCGpZu1gEeZMd9S4_DZfHbdgbHD_QgexoaxIX22bK9WKv0JMWKDuCvlZFILXR3_7_dtGg-0z4gruNCvXfWjub94aMD3ffpP9NE8ga_x_hD3odMTWNfffdPkz8cF65RU0OS0Uosz6Ud5iXYU6mVrEBzw1uiEig==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE1WgEM3eZDcHrGPBRo1qy3ej8at9HTgvlH2tdFU4fPhTj7qpfgx8cIVVp7hgenx4Zg6O99Iixxj_W2qGk6bUhWZrXiGiJKawKSbXCPJD5qn1jCmo9kWqQpPYAnA7N9hjG5D5CdxJ8==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF105W-FwxePN9Y0pPoNxfCmdpy-mkguIFgFLsCl2AoAJO4ChO0MsuicwwiYtPQSezxBnO2dPPnFfbQIJK_EdW0lag9XE36Sxx5MeZIzSrReADe3nplThfJn-c9Zpb6H43K0Z51ERvnFSmP9u9LDxs53UNlR8Agp53ii-aDN6I4_45u746vLMRQaX3h1m2TXwZy6smxdpH7cILeHLHysr905NJy1M8WtO5LwihX1-Nv99ed9WikDwCRMebThuFKFzyZwSNPKzVB2jUi8GE-OQ3BKm0JvooQyg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFvTlelxzwn-veWh63WqRrSeyegcXG4UW2AG-MbPuKy0n_3c_vY9Cf4SqluKDGfK3Cm3AK5mMZcIAwSOA0wj5jxVY23sooDHsWI2NNTpUzz5ZyEu2NTPfh988q3qSYC7XGJCuH8ddNl0rm9eIqGogQTOheNq-DYsJiZoIYdqLdObWitLMlEt1XZu7WBqayKaFt-WkRouP2r-pQnQ5ldmuVZQ8qPGQd1fkQUS1j5xvU6Sr8Be79vWQ==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGtXve8b58rBdVvsXknNu13P0uoNylL5-3AylIuPPPp0jDkZhtNO46caVlaASnSfDH3Zs3LdS4gzFuQFvBof0rKU2o81xSMVEqmKnVyaQHNKpUfkOin4LURHEYYrmC39T9rVXbXuMVcsOpCHt4-m283rSmTenh7TYZiuC4fu7GlcvIXZOxU3DqWzsVqJ9Af3bkV4lcOIpgdI3EI0a-S3cPNgdHnAw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFh53wMzTPTW3HU-ZmTCqHORiYdQoVYBTFOrSgpwpgQXnUrumdUvMHsNy9kW3k0zixjzbNGBbtYJGlEdFJDSOToAu7EokGA3xkRCD3VHUKT6QwEy9YkAbGKgGo-KtVhEb1IkeH6iU1mGz69oI1uZ7aV_6iOK6DmKunwNGNBpwf4v29P111IDa0QTz1cTI5vgwyeUtXxRM0uIue259HvNag6oxjRVv5sVA==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGP0l8MvGGGDSiU4ccR1L1EFDvwKBJYUQdsq_FrTM40Rs0poAp2vwvmy_Niqg_BtjYFsMDY3jnnXLZNdTrrQTXIz4mnEtshw1UHBe8TmWVBV4T0cyhIs_08hu7cR_f-UXKI-iKXb6SbqX0XZbKGM2gt6VzO1iMA0ATAlt-L3cD3XEk5T6q5GGFE13A==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGF5bvVFzWRAhnxBDwGaM0V4NI5tgYfYfX55NXjyG63H02H9_9vapm0DHp6i1AlTp2UIUKYdeAAO1A14kQ_btTJ5g8jOOoIlL9k2NyO4guR4jPfom-t5y9Qnt0gQ6mfNJNgtD7L0NQbm_Di9aJiIVVne8R1Bk8paUUT15VKWGIwaMV4Zczo65dLwfngoKl3ZXfGXxObZHPCzOXFCmq2yG0GCdwIsw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFOoVG8acYDIzeQ_Xn1FFOGNge2M3RnaW0scF_do4EW9H98g2N4yVrvYY020RCKenot4uTHA8quTrR1RGH4rD218sbRbzx1RGdvnaWC49MFHTi___Kt6MUUSi0KeU-A4Tly_CPyJ9r5ldH5ltEWla9S7WtFoBBKRZgmAjbHoKogP90GZpXaonDa8jNlzYX41-n281j8OzSeQNo_odVXnA4Wj0Or==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGGvw_r_YbIWPtD9indJ0s0MrQ8hIDD1_p5cuuzSvjYkZh4R-d-5HDKIhZroeSk7x7O1yMHcs1zZajc6wNjWx22BXLmk9CTfgyAVHwsuA8QNkGH8w6-msaWoV5AoEoA1Y-WRiN7oLZKiIaI5n2WTKuOZS92YX6MF01u9HnVof0BgCvzs_QyqT39gNyHa5J0N84Qt2OyCvYa4VAW6A==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGRMq5NALR5vgBqvYqtU9IlUksWamVxV6PFU4C1-uixhxkmXwmRx6WevN-tcPlRCWvHF-tOLusVLc5qZUhtgJw9iH2kA7RQ8CraRvNe2amVApvNHc7BKiNbJpMIojHiCpL6DaJUtOIjOuCXTzjitRb8BkV_KXJltXLzOEYd-4mj5HGCjnz6rQ7wtjUCgkGzP4weHufAgTriP_NXPae5XGJ55LoTVmeL-3_Bi4pXb72GU09kenkV==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEIaOIc_X_vElCOGoQ0ykhDBHQeSw6aTMSDVb22Cw9kfqRyk82Tq5EAzNSYvEbcVh3DumU6IqIXYAs2_b2cG8D_rI5FT832f8CfudClSWQPQdATf1TR18NNZi1ha9b3xvSSdwXv0I6jiksgkK68QCjU==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEqL-g2EeMSTxzKSBq41XvefuYb7ckIzdbYkYvNgYkBa9fLQGFWxn_1ZIMtgwDSc_zXEhO-g1u3Fnw6ku8OHUNMozldIbeRt0oxR8F0X1WFg6hggr8uhikwfh3zwdfkN4Z4Mfgf4zaoTuviTEnxo8M==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGoNBIDy75zXPX4xsrUOpZLHx_JSCi99MXPiJZLhzm7T1fj82pd17sOJvTvHgBC-q2bZ8vsrt4aHiBYNmcSlTXoREaAFhYBzukvnBuEZjuMbYV3quIn2g3I0dT--os1SHWd2AKAdfzBXPjIGP_n-CWmA_JP7tKrY56EHbQz2A_ues9PBRolqFlkkxTGuA_oZKQ4sKN3TuGQbQeIsbS2WgL4OTYlWVibB-w==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEWxeO0NbXNKswup5fm8F-MrXoFwrKd-bMdHuqmuZteYorKbul5fQd-QrSEj3txQtad0tCFU1Be6FHCdEofBqejXkIviOVyI5hCuEW05BWhuRZDT_s6gQgoUvIskLDDKbQr9VqJG9Xu7T1t0eLnEaNAjVoIuAM2btKDQcE6E2R6-MjOw5YIwpB7NYLe4MMd4tpSCCEMLG95WZ8mAmfu5PL5vsMIRddPpcuxW9A=="
      ],
      "search_queries_used": [
        "Vicentin S.A.I.C. Japan office",
        "Vicentin S.A.I.C. Tokyo subsidiary",
        "\u30d3\u30bb\u30f3\u30c6\u30a3\u30f3 \u65e5\u672c \u30aa\u30d5\u30a3\u30b9",
        "\u30d3\u30bb\u30f3\u30c6\u30a3\u30f3 \u6771\u4eac \u652f\u793e",
        "Vicentin S.A.I.C. Asia Pacific",
        "Vicentin S.A.I.C. Singapore office",
        "Vicentin S.A.I.C. employees",
        "Vicentin S.A.I.C. LinkedIn",
        "Vicentin S.A.I.C. company profile",
        "Vicentin S.A.I.C. Japan exports news",
        "Vicentin S.A.I.C. Asia trade news",
        "Vicentin S.A.I.C. Japan hiring",
        "Vicentin S.A.I.C. Japan press release",
        "site:linkedin.com \"Vicentin S.A.I.C.\" Japan",
        "site:linkedin.com \"Vicentin S.A.I.C.\" Asia Pacific",
        "site:linkedin.com \"Vicentin S.A.I.C.\" hiring manager",
        "Vicentin S.A.I.C. scandal",
        "Vicentin S.A.I.C. downsizing",
        "Vicentin S.A.I.C. financial trouble latest"
      ],
      "verification_gaps": []
    },
    {
      "company_name": "PROMEDON S.A.",
      "hq_country": "Argentina",
      "in_scope": true,
      "out_of_scope_reason": null,
      "asia_tier": "C",
      "asia_tier_evidence": "Promedon S.A. is headquartered in Argentina, with commercial offices for EMEA and APAC markets located in Kolbermoor, Germany, under Promedon GmbH. While they are present in over 60 countries across LATAM, EMEA, and APAC, and list distributors in several Asian countries (e.g., China, India, South Korea), Japan is not explicitly mentioned as a direct branch office or named distributor. The company visited Japan for business discussions in 2019, indicating past exploration of the Japanese market, but no recent (last 12 months) signals for a permanent entity or direct Japan operations were found.",
      "industry_primary": "Medical Devices",
      "industry_weight": "Lower",
      "company_size": "Mid",
      "employee_count_estimate": 576,
      "why_it_fits": "Promedon S.A. is an Argentine medical technology company, aligning with Wendy's Spanish-speaking Latin America HQ criteria. Their global presence includes the APAC region, with commercial operations managed from their German subsidiary, Promedon GmbH. Although there's no direct Japan entity, their model of serving APAC markets through distributors, combined with previous business discussions in Japan, indicates a potential for roles focused on market development and distributor management in the region. Wendy's extensive cross-functional commercial experience, including B2B, marketing, operations, and negotiations within multinational environments, would be highly valuable in a company seeking to grow its presence in complex markets like Japan. Her business-proficient Japanese (JLPT N2) and fluent English are crucial for navigating the Japanese market, even if indirectly, and bridging communication with the German-based APAC team and local partners.",
      "confidence": "Medium",
      "confidence_reason": "The company's HQ and industry are clearly defined and within scope. The APAC operational structure is well-documented as being managed from Germany, serving the region via distributors. However, explicit recent signals for Japan-specific market development or direct hiring in Japan are not available, leading to a 'Tier C' classification and reduced confidence in immediate, direct Japan-based opportunities.",
      "role_archetypes_likely": [
        "Trade Marketing Manager / Specialist (APAC)",
        "Business Development Manager APAC",
        "Partnership Manager / Alliance Manager APAC",
        "Pricing Manager / Revenue Manager"
      ],
      "flags": [
        "Industry (Medical Devices) is a 'Lower weight' fit for Wendy's background.",
        "No explicit recent Japan-specific market activity or hiring signals (last 12 months)."
      ],
      "suggested_next_action": "Message Marcelo Olmedo, Founder & CEO at https://www.linkedin.com/in/marcelo-olmedo-4b711a12/",
      "sources": [
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEkFfOSTdxhrkWSh6mRx0zHdiIp9l3PaApSPnHJBizVaXRYzbFR29lyVZx6zVuI32WYCTqWVcgs8_RPGN_38Sk5t583fL1LzXysSm3Xqz8jdkzK-aG1LpmWDI9sC8Mukg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGtLKBPSuDIaQCNaCkv5PQRzS0pbBnEddN9DR2n28HVD1BheDwPa1jRu2xbq0RZ0FFXbhg-aK2gBW5cMJFXjpBblhC_mRJncyRHYnHEI0GzWCtRe0uhX7BE-vBmjg==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH_qhEqW4gN9wCrBY4mY-Tu2sKh7cD9G-O7_T2TshMrjXNCCUil_FZTBCmj_ey8rmxXESjpxTACzXBsWC5dtFqIooCk4cpD_vtyD8_2RF-1W4R7cL6Wg9VVsJ2fSoLurZ-zKYyQQw==",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFDzT7kiJOJHzlGIY2a12S9OUTyqNCqWXrqqg6WJrXv0vqyvjyGRsiPWr8aS2BOZBFP5A-5Likfx1303HYJuXt6YcPMLDCiTL6jXyjcqDjHvEO4ZmucfQYe-5Fbrt8=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGID8X_GNf6DUejloO4etkCx1Gj_VuXtkTj37y8b-6GhKQ0blsnDbxA2zKZTfX5Td8SLxDFuITlhn-wUHWqs5K8d3c2QzLucWP5wpq33HKtN1tfMCjA8jdaEMIEFUInoE86cyBB",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGuBKJtOocpGyClavmdwuzEJ_Diop3HGLLDJsXZMpAKzZwUYTbqxcPFK-eDio8GrJ8A9YLpLEJAjD6c9OKmFW6ncKnEALhEw9S3KezZjOdXd7SSaoccUjrQxekSWis3LV8=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEhRid3vm9t9ci3nUqSRwjppdND11BU3j_1GFqGd7cPn98FWJlzSJOa9vIaOphwka8L91DZVml2z9TeDsFhoXSbGZSmCkym9myshyp9rxORYwH8_7Qf0otp_g-nbpXdqbes2dvmR1hlBNTrtUPZ9WLeq5BwIji2j222yl-S=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFkevMSsUZYmCfzqQv23XqFFvYPFdFGwuUF5_5yvmwI4s9yYTOcVLfk_BJsPAIOYMvl5VyHkt68U_iaE6n1hH5_S-iUorScJAgywwM6QXev5w_lDm4Cyd8sZ1xR_SpLE1x3vzBXZgntgTnSVcUk069VR61AFKKd8RjqIK9CyepUBFcRtyzil-T9mW-VxM6QfeI=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHXbvMUfrywBVDmarJ0U_O2vDykRiHRDt4ZsorKZDJu2VdyeNazjM7GlOv4KvnJHTDnUqEfijNym0xEcMzh4qjsS1Zwdx5HGi_pDRGxUVH4MZOqmCkVH-u1k44B0EU5hvh98xU=",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGUA_8j214KW8TObE2Fs0QnU4qJGi3rfgwjb1_b4kgSzKDIxGmd4SYkJIwhWOzA36DfdNN_zbuJzWzc9AU-PrpJTQeIXGFXzlZ3wl-qQNnD_ogFVtH99auO6rn6YA=="
      ],
      "search_queries_used": [
        "Promedon S.A. headquarters",
        "Promedon S.A. employee count",
        "Promedon S.A. Japan office",
        "Promedon S.A. Tokyo subsidiary",
        "Promedon S.A. Asia Pacific",
        "Promedon S.A. Singapore office",
        "Promedon S.A. Japan news",
        "Promedon S.A. Asia news",
        "Promedon S.A. LinkedIn Japan",
        "Promedon S.A. Medical Technology",
        "Promedon S.A. scandal",
        "Promedon S.A. downsizing",
        "Promedon GmbH APAC LinkedIn",
        "Promedon Global Business Development LinkedIn"
      ],
      "verification_gaps": [
        "Lack of explicit recent (last 12 months) signals about direct commercial activity or hiring in Japan.",
        "No specific LinkedIn profiles for hiring managers or key APAC commercial leads could be readily identified via direct search queries."
      ]
    },
    {
      "company_name": "Ferreiros y Vilela S.A.",
      "hq_country": "Argentina",
      "in_scope": false,
      "out_of_scope_reason": "Tier D: Export-only, no on-the-ground Asia presence. No verifiable Japan entity or APAC regional hub covering Japan was found.",
      "asia_tier": "D",
      "asia_tier_evidence": "Searches for 'Ferreiros y Vilela S.A. Japan office', 'Ferreiros y Vilela S.A. Tokyo subsidiary', 'Ferreiros y Vilela S.A. Asia Pacific', and 'Ferreiros y Vilela S.A. international presence' did not yield any results indicating an established entity or regional hub in Japan or Asia. The company's import/export data shows activity with Brazil, but no trade with Japan or other Asian countries. The prompt's note about a 2019 visit to Japan for business discussions by an Argentine auto company could not be specifically corroborated for Ferreiros y Vilela S.A. through web searches.",
      "industry_primary": "Automotive and auto parts (Transportation Equipment Manufacturing)",
      "industry_weight": "Medium",
      "company_size": "Mid",
      "employee_count_estimate": null,
      "why_it_fits": "Ferreiros y Vilela S.A. is an Argentinian manufacturer of mechanical and electrically assisted steering boxes, operating within the automotive parts sector. While the company's core industry aligns with Wendy's 'Medium weight' experience in Automotive and auto parts, and its Argentine HQ is in scope, there is no verifiable evidence of any commercial presence or active plans for expansion into Japan or the broader Asia-Pacific region. Its international trade activity primarily involves Brazil. Therefore, without an established presence in Asia, the company does not currently fit Wendy's geographical scope.",
      "confidence": "Low",
      "confidence_reason": "The HQ country and primary industry are well-verified. However, the critical 'Asia Operations' criteria cannot be met due to a complete lack of verifiable evidence for any Japan or APAC presence for this specific company. Employee count could not be determined without purchasing a report.",
      "role_archetypes_likely": [],
      "flags": [
        "No verifiable Japan or APAC presence found.",
        "Specific employee count for Ferreiros y Vilela S.A. could not be determined without paid report."
      ],
      "suggested_next_action": "Since no verifiable Japan or APAC presence was found, further direct action is not recommended at this stage. Wendy should focus on companies with confirmed in-scope Asia operations.",
      "sources": [
        "https://www.fyv.com.ar/empresa/es - Ferreir\u00f3s y Vilela S.A. | Uni\u00f3n Industrial de Tigre",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEx95rtefXzn-2PsPtMeB2KyAoyfJlkBBVplAdFQ9pE2m_5eGIbvtX0mbMV2uOONgXbcZPnkFVDtfLFDX4u4IJt6Li5_vW0hlT7qSJjmaXuj1BGe1EMCTMCVaQn1FR1n7GfUCeORJryWqI23zQSD0FtfUr1MSrn2qw6NY204x-HQknwxnAswyuRl6fJ - Ferreiros y Vilela S.A. Company Profile - Argentina | Contacts & Key Executives | EMIS",
        "https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFxYLCNrC7j77SjwoQXtSGRdXXfUZLAg_y_MKyeBZSIbnK43yED4BheBlUk96QLv43C2q-5VwreLlnBO0JsNpHBrpVe2MtVx1WxNNWXSkm9HdLTa9Y5anzu-uHw83cJTWbpzUadqLniSbsi1JDalJ5da39zz6OPyzXBhZ1Z0sf3ffLhLnk4L0q43PMzuc9pRiAvMk9qeFQ1jyr5cNJXNFzwomkZ1PQ-Yfn38-3XQQ93bIVMXW-T4aruKpFDiWmiloI - Importaciones y Exportaciones de FERREIROS Y VILELA SA SISTEMAS DE DIRECCION - Veritrade"
      ],
      "search_queries_used": [
        "Ferreiros y Vilela S.A. Argentina",
        "Ferreiros y Vilela S.A. Japan office",
        "Ferreiros y Vilela S.A. Tokyo subsidiary",
        "Ferreiros y Vilela S.A. Asia Pacific",
        "Ferreiros y Vilela S.A. Singapore office",
        "Ferreiros y Vilela S.A. employees",
        "Ferreiros y Vilela S.A. news Japan Asia",
        "Ferreiros y Vilela S.A. LinkedIn",
        "Ferreiros y Vilela S.A. official website",
        "Argentina PYMES definition employees",
        "Ferreiros y Vilela S.A. international presence",
        "Ferreiros y Vilela S.A. export to Japan"
      ],
      "verification_gaps": [
        "Confirmation of any commercial presence or activity in Japan or the broader APAC region for Ferreiros y Vilela S.A.",
        "Specific employee count for Ferreiros y Vilela S.A.",
        "Corroboration of the 2019 business discussions in Japan specifically for Ferreiros y Vilela S.A."
      ]
    }
  ]
};